### ISSUE TITLE
Demo/Examples Error

### ISSUE THREAD

**Issue by shortwavedave** [darwin-education/resium#102]
Trying to see the entity/graphics example (https://resium.darwineducation.com/examples/?path=/story/entity--graphics) results in an error:

> DataCloneError: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered.
> Error: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered.
>     at https://resium.darwineducation.com/cesium/Cesium.js:30309:31
>     at Promise.then (https://resium.darwineducation.com/cesium/Cesium.js:1147:34)
>     at when (https://resium.darwineducation.com/cesium/Cesium.js:1010:34)
>     at TaskProcessor.scheduleTask (https://resium.darwineducation.com/cesium/Cesium.js:30298:16)
>     at loadAsynchronous (https://resium.darwineducation.com/cesium/Cesium.js:102841:63)
>     at Primitive.update (https://resium.darwineducation.com/cesium/Cesium.js:103548:17)
>     at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:135934:27)
>     at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:135934:27)
>     at PrimitiveCollection.update (https://resium.darwineducation.com/cesium/Cesium.js:135934:27)
>     at updateAndRenderPrimitives (https://resium.darwineducation.com/cesium/Cesium.js:244342:27)

![image](https://user-images.githubusercontent.com/22798574/61772061-68077e80-ae02-11e9-8b58-6d56927c31e7.png)

**Comment by rot1024** [comment]
I could not confirm the error in my MacBook Pro 13 (OS X Mojave) and Chrome 75.

It seems to be an error due to your environment or device.
