### ISSUE TITLE
Re-rendering Entiny when position is changed

### ISSUE THREAD

**Issue by Cootcha** [darwin-education/resium#104]
Hi, I am trying to make animation with dynamically position changing. When i look at direct to Entiny with camera's FOV, entity is re-render in every animation step. If i look to React debugging tool, i see, that props was changing and component was rerender. When camera's FOV is not direct to Entity, Entity doesnt rerendering after change props. I must manually change camera position and animation has continuing. Redux and React in every step rerendered component with Entity, but on globe is not changed. Entity is stoped on last position where was render. When i add animation step to Viewer component, animation works great, but every komponent in viewer will be rerendered and map request destroyed app speed.

[https://drive.google.com/file/d/1mMJKyyk2zUTKNvYEYHttqxADqGetErAA/view?usp=sharing](url)

**Comment by kurohune538** [comment]
You should try to use `onPostRender` Event in `<Scene>` component.
https://resium.darwineducation.com/components/Scene

```
const EarthView: React.FC<> = () => {
  const handlePostRender = () => {
    // write your code here
  };

  return (
      <Viewer>
        <Scene onPostRender={handlePostRender} />
      </Viewer>
  );
};
```
Camera onChange event isn't called every rendering.

If I missed the point, paste your code here :)

**Comment by Cootcha** [comment]
`<Viewer>`
  `  <Scene>`
   `   <Globe />`
   `   <Camera />`
   `  <ImageLayer />`
   `  <Entity />` // entity container - only props for this component. Only Entity was rerender.
  `  </Scene>`
`</Viewer>`
When i rerender Scene, all Imagelayer will be rerender.. and period of rerendering is 10 times / second. I need rerender Entity position and update it in map.

**Comment by kurohune538** [comment]
Do you want to update ONLY Entity?

We want to reappear your case. so please put your entire codes here.

**Comment by Cootcha** [comment]
Yes, Only Entity component. I have own props for scene, own for entity. Entity is child of Scene. When i change entity props, component is rerendering and entity move. But when i move camera's FOV out of entity, props change, entity is on last position but in entity props is new position and component was updated. When i have camera's FOV on entity, entity is moving,but scene is not rerendering and this is correct.
My App is connect to many services and its impossible to insert working code.

**Comment by Cootcha** [comment]
```
import React from "react";
import { hot } from "react-hot-loader/root";
import { Cartesian3, Color, Fog, SkyAtmosphere } from "cesium";
import { Viewer, Entity, Scene } from "resium";

class TestEntity extends React.Component {
  constructor(props) {
    super(props);
    // Don't call this.setState() here!
    this.state = { counter: 0 };
  }

  render() {
    setInterval(() => { 
      this.setState({ counter: this.state.counter + 0.01 });
    }, 1000);
    return <Entity
      name="Tokyo"
      position={Cartesian3.fromDegrees(139.767052 + this.state.counter, 35.681167, 100)}
      point={{ pixelSize: 100 }}
      description="hoge"
    />;
  }
}

const FOG = new Fog();
const SATM = new SkyAtmosphere();

SATM.show = false;
FOG.enabled = false;

const App = () => (
  <Viewer
    full
    timeline
    requestRenderMode
    animation={false}
    vrButton={false}
    geocoder={false}
    homeButton={false}
    fullscreenButton={false}
    baseLayerPicker={false}
    infoBox={false}
    navigationHelpButton={false}
    scene3DOnly
    selectionIndicator={false}>
    <Scene
      debugShowFramesPerSecond={false}  // fps/odezva - pravý horní roh
      sunBloom={false}
      fog={FOG}
      skyAtmosphere={SATM}
      fxaa
      backgroundColor={Color.ALICEBLUE}
      highDynamicRange={false}
    >
      <TestEntity/>
    </Scene>    
  </Viewer>
);

export default hot(App);

```
Same problem, Its EXAMPLE from your RESIUM repository

**Comment by Cootcha** [comment]
i found problem. Its "requestRenderMode". When i removed this. Everything works great. So Its my (my team) mistake.
