### ISSUE TITLE
jest does not work with Resium

### ISSUE THREAD

**Issue by delenius** [darwin-education/resium#105]
I set up resium using the craco approach.
Invoking jest causes `ReferenceError: requirejsVars is not defined`, as discussed [here](https://github.com/facebook/jest/issues/1914).
The solution described there does not work with CRA because there is no way to pass a CLI option to jest(?).
Could this be taken care of automatically by `craco-cesium`?

**Comment by rot1024** [comment]
craco-cesium does not support test for components using Resium and Cesium, because Cesium depends on require.js (AMD) and web APIs (WebGL, WebWorker, ...). If you want, you have to mock Cesium in Jest, but it seems to be hard.

related: #34

**Comment by delenius** [comment]
@rot1024 , I know that's the problem... We need a solution ;) It is also not easy to switch to another test framework, given how CRA is structured. I guess the only solution is to eject and then use something other than jest?

**Comment by rot1024** [comment]
Hmm... You may need to do one of the following:

1. Give up testing of components that uses Resium and Cesium. Components without Resium and Cesium are still testable.
2. Eject the CRA project and start using other test runner that can run tests on the web browsers, for example, Karma.
3. Write mocks of Cesium objects (components that uses Resium are testable if Cesium objects are correctly mocked)

**Comment by delenius** [comment]
I need to test with real Cesium outputs, to sanity check my coordinate transformations and whatnot, so I guess (2) it is...

**Comment by rot1024** [comment]
Yes... I can not follow up with the karma installation method, so please let me know if you can.
