### ISSUE TITLE
3DTileset not loading

### ISSUE THREAD

**Issue by johnagustin** [darwin-education/resium#106]
There's nothing happening when I try to load my own 3D tileset file.

```
import { Viewer, Cesium3DTileset } from "resium";

const App = () => {
  let viewer;

  const handleReady = tileset => {
    if (viewer) {
      viewer.zoomTo(tileset);
    }
  };

  return (
    <Viewer
      full
      ref={e => {
        viewer = e && e.cesiumElement;
      }}>
      <Cesium3DTileset url={require('./assets/tileset.json')} onReady={handleReady} />
    </Viewer>
  );
};
```

But it is fully working using vanilla Cesium.
```
const viewer = new Cesium.Viewer('cesiumContainer', {
    homeButton: false,
    timeline: false
});

const tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
    url : './assets/tileset.json'
}));

viewer.zoomTo(tileset);
```

I even tried using the tileset given by this Cesium sample ([Cesium Sample Tileset](https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/tree/master/tilesets/TilesetWithDiscreteLOD)), and the result is the same. It's working with the vanilla but not with Resium.

Thank you! Hoping to receive an update soon.

**Comment by rot1024** [comment]
please fix:

```
<Cesium3DTileset url="./assets/tileset.json" onReady={handleReady} />
```

**Comment by johnagustin** [comment]
I am using resium in a webpack environment that's why I am using require to reference the location.

**Comment by rot1024** [comment]
Ok. Cesium3DTileset does not support direct loading of the tileset data, so please use public directory.

1. Put the `tileset.json` in `public` directory in the project.
2. `<Cesium3DTileset url={process.env.PUBLIC_URL + '/tileset.json'} onReady={handleReady} />`

**Comment by johnagustin** [comment]
Ah, I see. Thank you! Will close this one already.
