### ISSUE TITLE
Entity in list updates unnecessarily 

### ISSUE THREAD

**Issue by shortwavedave** [darwin-education/resium#108]
I have a list of entities, each with a unique key property, that appears to re-render - it flickers. When the mouse moves over the entity there is a state change, but it is not a property of any of the elements. I've tried it with and without a CustomDataSource.

```
<Viewer ref={(ref: any) => this.topComponent = ref} full >
        <MapContextMenu cmdStateHandler={this.handleCmdChange}/>
        <ScreenSpaceEventHandler>
            <ScreenSpaceEvent action={this.onMouseMove} type= {ScreenSpaceEventType.MOUSE_MOVE} />
        </ScreenSpaceEventHandler>
        <CustomDataSource name={"corridors"} show>
            {entities}
        </CustomDataSource>
</Viewer>
```

Here's an example with one entity:
![entities](https://user-images.githubusercontent.com/22798574/62003039-4c151d00-b121-11e9-9caf-086a57dcd97d.gif)

Here's the tree in the react debugger:
![image](https://user-images.githubusercontent.com/22798574/62003095-626fa880-b122-11e9-839e-e9957f012f06.png)

The entity code:

```
export namespace Entity {
    export interface Props {
        id?: string;
        key?: string;
        name?: string;
        description?: string;
        position?: PositionProperty | Cartesian3;
    }
}

export class Entity {
    protected wrapEntity(entity: JSX.Element | null, props: Entity.Props): JSX.Element {
        return (
            <ResiumEntity
                key={props.key}
                id={props.key}
                name={props.name}
                description={props.description}
                position={props.position}
            >
                {entity}
            </ResiumEntity>
        )
    }
}
```

Any ideas?

**Comment by rot1024** [comment]
I want to see content of `entities` and `onMouseMove`, or else I don't know what causes the problem.

**Comment by shortwavedave** [comment]
The way my code updates entities and onMouseMove is somewhat convoluted, so I won't bother you with sorting through all that mess. 

I did discover that the flickering only occurs if there is only one entity. If there are more than one entities, then they do not flicker. By adding an empty entity it solves the issue, so I'm going to close this question for now. If I figure out what the issue is, I'll update this issue.

Thanks

**Comment by zicodasilva** [comment]
@shortwavedave did you ever figure out why the flickering occurs if there is only one entity on screen? I have the same issue at the moment, and would like to know if there is a reason for this behaviour before I implement a "fix" for it.
