### ISSUE TITLE
GroundPrimitiveCollection & GroundPrimitive are not exported as components

### ISSUE THREAD

**Issue by JelayDark** [darwin-education/resium#110]
Hi!
I found out, that you have added these components with the introducing  v. 1.3. But we can not use it, cuz you didn't import them into and didn't export them from` src/index.ts `file

**Comment by rot1024** [comment]
Thank you for reporting. I forgot exposing them. I'll fix it soon.

**Comment by rot1024** [comment]
Hi, I exposed `GroundPrimitiveCollection` and `GroundPrimitive` component, and released v1.7.0. Try it!
