### ISSUE TITLE
difference between sourceuri and data in GeoJsonDataSource

### ISSUE THREAD

**Issue by shortwavedave** [darwin-education/resium#111]
For the GeoJsonDataSource component, what is the difference between the properties "sourceUri" and "data", which can also be a uri?

**Comment by rot1024** [comment]
- `data`: a url, GeoJSON object, or TopoJSON object to be loaded. (main argument of Cesium's `GeoJsonDataSource.load`)
- `sourceUri`: Overrides the url to use for resolving relative links. (an option of Cesium's `GeoJsonDataSource.load`)

See also: [GeoJsonDataSource](https://cesiumjs.org/Cesium/Build/Documentation/GeoJsonDataSource.html)
