### ISSUE TITLE
Type EventKey has a long declaration which I don't agree with.It is 'never' that I can't understand

### ISSUE THREAD

**Issue by hachimei** [darwin-education/resium#113]
The code is from CesiumComponent
`export type EventKeys<T> = { [P in keyof T]: T[P] extends Cesium.Event ? P : never }[keyof T];

export type EventkeyMap<T, P> = { [K in EventKeys<T>]?: P };`
Is the EventKyes { [P in keyof T]: never }[keyof T] ? Finally the type of it is  never, the type of EventkeyMap is "{}" by the following test:
`
export interface ClockCesiumEvents {
  onStop?: (clock: Cesium.Clock) => void
  onTick?: (clock: Cesium.Clock) => void
}

type a = EventkeyMap<Cesium.Globe, keyof ClockCesiumEvents> // a = {}
`
The code is from Clock.

**Comment by rot1024** [comment]
Do you mean:

```ts
 type a = EventkeyMap<Cesium.Clock, keyof ClockCesiumEvents>;
```

The following code suggests that the `a` type is empty object type because `Cesium.Globe` does not any event properties. This issue is caused because `Cesium.Globe` type lacks event fields.

```ts
 type a = EventkeyMap<Cesium.Globe, keyof ClockCesiumEvents>;
```

I feel that `@types/cesium` is less complete and need more improvement.
