### ISSUE TITLE
GeoJsonDataSource 'show' property not behaving as expected

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#114]
When it comes to show/hide a GeoJsonDatasource by changing the state of the associated variable by making use of a Check box, it works fine when the GeoJsonDataSource is a line/polyline, but it doesn't works when the datasource are polygons. The polygon datasource is not particularly large (around 200 polygons). The only way I have seen the polygons are back to the map is when you change any other property, such as alpha, but not by putting 'show' to TRUE. This is an extraction of my code:

```
const mydata = 'URL to the GeoJson datasource';

class MyMap extends Component {
    constructor(props) {
        super(props);
        this.viewerRef = React.createRef();
        this.sceneRef = React.createRef();
    }
	
   state = {
   PleaseShow: true,
    ...
    };

    handledataShowChange = (e) => {
        e.target.checked ? this.setState({ PleaseShow: true }) : this.setState({ PleaseShow: false });
};

    renderGeoJsonDataSources() {
    const { PleaseShow } = this.state;
    return (
        <Fragment>
        <GeoJsonDataSource
            data={mydata}
            show={PleaseShow}
            fill={Color.RED}
            clampToGround={true}
        />
        </Fragment>
    );
}

render() {
    return (
        <Viewer
            ref={this.viewerRef}
            ...
        >
            <Scene ref={this.sceneRef} />
            {this.renderGeoJsonDataSources()}
        </Viewer>
    );
}
}
```

And again, it works fine with lines.

**Comment by rot1024** [comment]
Is this issue not related to #115 ? This issue is probably due to Cesium itself.

**Comment by pyonono** [comment]
No, it is not, because in this case, the polygon loads correctly (it is a simple polygon though). The problem is that if you change the property Show, from true to false (after the first load), it disappears from the map as expected, but when you change back from false to true, the polygon doesn't pop up.

**Comment by rot1024** [comment]
I fixed the bug and added a story to storybook. Please try resium v1.9.0-beta.0.

https://resium.darwineducation.com/examples/?path=/story/geojsondatasource--show
