### ISSUE TITLE
GeoJSON datasource crashes (EllipsoidRhumbLine ..issue)

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#115]
I have noticed this issue a few days ago when I got this error when loading a set of polygons as GeoJSON datasource type:

DeveloperError: EllipsoidRhumbLine must have distinct start and end set.

Apparently this error has been spotted before in May-2019: https://github.com/AnalyticalGraphicsInc/cesium/issues/7864

It was something that was okay in 1.53 version, but it fails in newer versions.

It can be fixed by changing the ArcType to GEODESIC,

Is there any way within the GeoJSON component to change that inside? I haven't found any property related to that in the GeoJsonDataSource component.

What would be then the easiest here?

Thanks,

**Comment by rot1024** [comment]
How about this?

```jsx
<GeoJonDataSource
  data={}
  onLoad={ds => {
    ds.entities.map(e => { e.polygon.arcType = Cesium.ArcType.GEODESIC; });
  }} />
```

**Comment by pyonono** [comment]
Well, the thing is that the Geojson datasource loads okay using just Cesium 1.53 (without resium). See below:

![image](https://user-images.githubusercontent.com/52279133/64291482-34bb2200-cf60-11e9-8180-cecd3ad4a3de.png)

But, when using that version in the package.json file: "cesium": "^1.53", the problem doesn't go away.

By the way, in your example, is 'ds' a variable where to load the URL of the geojson?

Thanks,

**Comment by pyonono** [comment]
By the way, this is the GEOJson in question if anyone wants to test it (please rename .PDF to .json)


[features.PDF](https://github.com/darwin-education/resium/files/3594480/features.PDF)

**Comment by pyonono** [comment]
Apparently the solution in Cesium would be:

var geoJSON = Cesium.GeoJsonDataSource.load( 'path_to_file', {
        stroke: Cesium.Color.HOTPINK,
        fill: Cesium.Color.PINK.withAlpha(0.5),
        strokeWidth: 3
});

geoJSON.then(function(data){
    // Change the arcType to GEODESIC, which is what it was in CesiumJS 1.53.
    for (var i = 0; i < data.entities.values.length; i++) {
        var entity = data.entities.values[i];
        if (Cesium.defined(entity.polygon)) {
            // entity.polygon.arcType = Cesium.ArcType.GEODESIC;
        }
    }
    viewer.dataSources.add(data);
});

But how that could be put into our Resium?

**Comment by jose-sanchez-morales** [comment]
Update: Apparently the dataset (.json) had self-intersecting polygons. I have fixed this, so now Cesium doesn't crash (it doesn't show that error message), but it is not solved as Cesium doesn't render the polygons correctly. Have a look at the attached picture. It draws artifacts. It could be related to that ArcType parameter as well. I don't know.
![image](https://user-images.githubusercontent.com/23268893/67372541-f7ddd580-f575-11e9-864c-fbc39208f769.png)

**Comment by rot1024** [comment]
I tried that with resium v1.9.0-beta.0 and cesium v1.63.1 and it seems to work.

![image](https://user-images.githubusercontent.com/3888696/68943733-5dc52200-07ef-11ea-841d-07c02887323a.png)

```jsx
import { Viewer, GeoJsonDataSource } from "resium";
import data from "./features.json";

const Component = () => {
  const ref = useRef(null);

  return (
    <Viewer full ref={ref}>
      <GeoJsonDataSource
        data={data}
        onLoad={d => ref.current?.cesiumElement?.zoomTo(d)} />
    </Viewer>
  );
};
```

**Comment by rot1024** [comment]
If the problem persists in the latest version, reopen this issue.

**Comment by jose-sanchez-morales** [comment]
Thanks, I will do
