### ISSUE TITLE
using cesium 1.62 release

### ISSUE THREAD

**Issue by jvarada** [darwin-education/resium#118]
Is it possible to use release 1.62 of cesium with resium? We're using resium with typescript and cesium installed via craco-cesium. We're interested in using the new EllipsoidGeometry elements. Using CZML definitions would be fine, we wouldn't necessarily need an element wrapper for it. If so, would it be just a matter of updating the cesium version on npm or would more changes be required from the resium point of view?

**Comment by rot1024** [comment]
In Cesium v1.62, new properties are added to Cesium's object, so we have to update Resium to add these properties to the components.

I'll update Resium as soon as possible.

**Comment by rot1024** [comment]
Resium v1.8.0 has been released now. Try it!
