### ISSUE TITLE
integrate "partial Elipsoids" entitie in Resium

### ISSUE THREAD

**Issue by arnaudiko** [darwin-education/resium#120]
A new entity has been added with Cesium 1.62

cesium demo: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Partial%20Ellipsoids.html&label=Geometries

**Comment by rot1024** [comment]
duplicated: #118

I am working on it now.

**Comment by arnaudiko** [comment]
ho cool thanks,
Sorry I dont saw this one
