### ISSUE TITLE
ImageryLayer does not render tiles for poles

### ISSUE THREAD

**Issue by mrlubos** [darwin-education/resium#121]
Hey, I came across a weird issue. When using a custom imagery provider on Viewer like this, everything is fine.

```js
<Viewer imageryProvider={myImageryProvider}>
  // stuff
</Viewer>
```

However, when we change the code above to this.

```js
<Viewer>
  <ImageryLayer imageryProvider={myImageryProvider} />
  // stuff
</Viewer>
```

We end up with this.

<img width="512" alt="Screenshot 2019-10-11 at 2 21 36 pm" src="https://user-images.githubusercontent.com/12529395/66654842-f84fa580-ec32-11e9-90a0-7a24c07ca976.png">

👆The tiles around poles are not updated.

The functional difference between examples 1 and 2 is to do with updating the `myImageryProvider` variable. In example 1, it re-animates the whole globe, i.e. we lose our state. In example 2, only the tiles are updated without affecting the camera.

**Comment by rot1024** [comment]
```jsx
<Viewer imageryProvider={myImageryProvider}>
  // stuff
</Viewer>
```

makes Viewer's imagery provider overrided with `myImageryProvider`. As a result, there are only one imagery provider.

But 

```jsx
<Viewer>
  <ImageryLayer imageryProvider={myImageryProvider} />
  // stuff
</Viewer>
```

just adds a new imagery provider: `myImageryProvider`, so the default imagery provider remains.

```
myImageryProvider
default imagery provider
```

So how about this?

```jsx
<Viewer imageryProvider={false}>
  <ImageryLayer imageryProvider={myImageryProvider} />
  // stuff
</Viewer>
```

**Comment by mrlubos** [comment]
Thanks @rot1024! Do you know what's the default imageryProvider setting for Cesium?

**Comment by rot1024** [comment]
According to [Cesium documentation](https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html), the default imagery provider is the return value of `createWorldImagery()`.

**Comment by mrlubos** [comment]
> According to [Cesium documentation](https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html), the default imagery provider is the return value of `createWorldImagery()`.

Thank you for your help!

**Comment by mrlubos** [comment]
@rot1024 Hey, so the solution you provided gets rid of the original issue, but creates a new issue. Switching between imagery providers leaves us with a brief moment when the Earth is blue (default colour when no imagery is provided) and this produces an unpleasant effect. I think we'd need to go back to the original solution and the original issue. We have one base layer (default imagery) and optionally we can have a styled layer. This produces the bug seen above. Do you think there is a better way that solves both problems? Thanks!
