### ISSUE TITLE
CesiumMovementEvent `startPosition` field is mis-named

### ISSUE THREAD

**Issue by markerikson** [darwin-education/resium#122]
This is the current definition:

https://github.com/darwin-education/resium/blob/295f75f5ecbd7379a6818ab23d1e161651979291/src/core/EventManager.ts#L46-L50

The field should be named `startPosition`, not `startPositon`

**Comment by rot1024** [comment]
Thank you for reporting. It will be fixed next version.

**Comment by rot1024** [comment]
v1.8.1 has been released. Try it!
