### ISSUE TITLE
Adding a HTML div element (toolbar, etc ..)

### ISSUE THREAD

**Issue by onurakdemir** [darwin-education/resium#124]
First of all, thank you for this great work.

I want to add Html elements on top the map. (Control Panel, toolbar, etc..)
How can I add these overlay elements?

**Comment by rot1024** [comment]
You can just add elements inside Viewer:

```jsx
<Viewer>
  <div style={{ position:"absolute", top: 0, left: 0 }}>hogehoge</div>
</Viewer>
```
