### ISSUE TITLE
This repository is not supporting cesium updated version

### ISSUE THREAD

**Issue by GuyChabra** [darwin-education/resium#126]
Hi,

When will you support the updated version of cesium & @types/cesium?

> "cesium": "1.63.0",
> "@types/cesium": "1.59.2

Cesium changed module declaration
`import Cesium from 'cesium'`
will return undefined.

Thanks!

**Comment by rot1024** [comment]
I'm working it now on next branch.

**Comment by rot1024** [comment]
Resium v1.8.1 has been released. Try it! Reopen this issue if you still have problems.

**Comment by GuyChabra** [comment]
Thanks!

**Comment by smonikantara** [comment]
I am still having this issue - `import Cesium from 'cesium'` returns `undefined`. I am using:

- React v16.8.6
- Resium v1.11.0
- Cesium v1.65
- @types/cesium v1.65.3
