### ISSUE TITLE
Show orbit

### ISSUE THREAD

**Issue by arturcarvalho** [darwin-education/resium#127]
Hi there,

Is there any way to show the orbit like the one in Celestrak? The orbit is the green line in the example below.

![image](https://user-images.githubusercontent.com/2487710/68387497-bbf26500-015e-11ea-9753-85e16a515f42.png)

Thank you and thank you for the library! :relaxed:

**Comment by rot1024** [comment]
This seems like an issue on how to use Cesium, not Resium.

To draw a trajectory, you can use PathGraphics or SampledPositionProperty in PolylineGraphics.

**Comment by arturcarvalho** [comment]
So I can access this Cesium functionality from Resium. I was not sure if you had to wrap it in some way. 

Thank you for your help! :)
