### ISSUE TITLE
In a create react app project,it still occur wrong when set alias.

### ISSUE THREAD

**Issue by qdxkrs** [darwin-education/resium#13]
./node_modules/cesium-react/dist/cesium-react.es.js
Module not found: Can't resolve 'cesium' in 'node_modules\cesium-react\dist'
i have set alias
---------------------------------
    config.resolve = {
        alias: {
            cesiumSource: "cesium",
            cesium: "cesium/Cesium"
        }
    };
--------------------------------

**Comment by rot1024** [comment]
For now, [this](https://github.com/darwin-education/resium/tree/master/example) is recommended.

I plan to write a document how to get started resium project with create-react-app.

**Comment by rot1024** [comment]
Hi, you can set aliases as bellow in webpack config. It will work.

```
resolve: {
  alias: {
    cesium$: "cesium/Cesium",
    cesium: "cesium/Source"
  }
}
```

See also [readme](../tree/master/README.md).

Reopen an issue if the issue persists.
