### ISSUE TITLE
CameraFlyTo

### ISSUE THREAD

**Issue by Flo-droid** [darwin-education/resium#132]
Hey, i'm pretty new to using Cesium and resium.
I'm trying to call my CameraFlyTo my entity at the first render, but it keeps activating since my entity is moving, is there a parameter that let you trigger cameraflyto only once at the beginning?

**Comment by rot1024** [comment]
No, but I added `once` prop to `CameraFlyHome/To/ToBoundingSphere` components.

Please try v1.9.0-beta.0.
