### ISSUE TITLE
ImageryLayer remount warning even when using useMemo

### ISSUE THREAD

**Issue by makeupsomething** [darwin-education/resium#136]
I am working on an application where our imageryProvider layers are variable based on some user. I use the useMemo hook as suggested in the documentation to handle this but I still get this warning every time the layers string changes.

`Warning: <ImageryLayer> is remounted because read only props have been updated: imageryProvider`

The code looks something like this, where the layers will be a string that changes based on user selections.

```jsx
const LayerRender = (props: Props) => {
	const { layers, show } = props;

	const imageryProvider = useMemo(
		() =>
			new WebMapServiceImageryProvider({
				url: `${some_url}`,
				layers,
				parameters: {
					transparent: 'true',
					format: 'image/png',
				},
			}),
		[layers],
	);

	return <ImageryLayer imageryProvider={imageryProvider} show={show} />;
};
```

**Comment by rot1024** [comment]
Hmmm it is strange, but there is no doubt layers prop changes every render.

**Comment by makeupsomething** [comment]
After updating resium version we no longer have this problem. Closing.

**Comment by Raza410** [comment]
I am using the latest versions but I am facing this issue. In my case, nothing is variable in imageryProvider, I am just using show prop of imagery layer to on and off them.
 
<ImageryLayer show={checkedItems.layer} imageryProvider={WMSprovider("layer")} />

const WMSprovider = (layerName) => {
  return new WebMapServiceImageryProvider({
    url: geoserverUrl,
    layers: `${storeName}:${layerName}`,
    parameters: {
      transparent: true,
      format: "image/png",
    },
  });
};
