### ISSUE TITLE
How to position Cesium3DTileset?

### ISSUE THREAD

**Issue by siljec** [darwin-education/resium#137]
Hi there, I'm new to cesium/resium.

I have uploaded a 3D-tile asset to https://cesium.com/ion/ and I'm able to render it, but how can I position it based on longitude and latitude on the map? 

```
import {hot} from "react-hot-loader/root";
import React from "react";
import {Viewer,Cesium3DTileset} from "resium";
import {IonResource, ColorBlendMode} from "cesium";

const App = () => {
    let viewer;

    const handleReady = tileset => {
        if (viewer) {
            viewer.zoomTo(tileset).otherwise(function (error) {
                console.log(error);
            });
        }
    };

    return (
        <Viewer
            full
            ref={e => {
                viewer = e && e.cesiumElement;
            }}
        >
                <Cesium3DTileset
                    url={IonResource.fromAssetId(58415)}
                    onReady={handleReady}
                    onClick={(position) => console.log(position)}
                    colorBlendMode={ColorBlendMode.HIGHLIGHT}
                />
        </Viewer>
    )
};

export default hot(App);
```

EDIT: Just realised that i could change the tile location in Cesium Ion when I uploaded a collada .dae file. Could not change the location with the .kmz file I tried first. Would be nice if you could overwrite that position in the code though, but adjusting it in Cesium Ion will do:)

**Comment by rot1024** [comment]
I have not ever used Cesium3DTileset via Cesium Ion, but it seems to be that Cesium doesn't have a function to overwrite positions of a Cesium3DTileset.
