### ISSUE TITLE
3DTileset not receiving any url

### ISSUE THREAD

**Issue by nadavtal** [darwin-education/resium#138]
Hello, i'm trying desperatley to insert a tileset in my 3dTileset component. how ever the "url" property is not working and not showing anything, also if i put an invalid address in it it doesnt show an error.
been trying for 2 days now with webpack without success.
any help?

**Comment by rot1024** [comment]
It may be a problem of Cesium or webpack, not Resium. You can try with raw Cesium3DTileset of Cesium.

```jsx
import React, { useRef, useEffect } from "react";
import { Viewer, Cesium3DTileset } from "cesium"; 

const Test = () => {
  const ref = useRef();
  useEffect(() => {
    if (!ref.current) return;
    const viewer = new Viewer(ref.current);
    viewer.primitives.add(new Cesium3DTileset({
      url: "YOUR URL"
    }));
  }, []);
  return <div ref={ref} style={{ width: "300px", height: "300px" }} />
}
```

**Comment by nadavtal** [comment]
Thank you very much. i still get the same result. the viewer is loading but not the 3d tileset. and no errors. i think too that it either a problem with cesium or webpack.
is there any way to get help to solve the problem? paid ofcourse. i;'m buidling a big app based on resium.
thanks alot:)

**Comment by rot1024** [comment]
You can use onTileLoad, onTileFailed, onReady event props to debug whether loading is done or failed.

```jsx
const Test = () => {
  const ref = useRef(null);
  return <Viewer>
      <Cesium3DTileset
        url="hogehoge/tileset.json"
        onAllTilesLoad={(...args) => console.log("onAllTilesLoad", ...args)}
        onInitialTilesLoad={(...args) => console.log("onInitialTilesLoad", ...args)}
        onTileFailed={(...args) => console.log("onTileFailed", ...args)}
        onTileLoad={(...args) => console.log("onTileLoad", ...args)}
        onTileUnload={(...args) => console.log("onTileUnload", ...args)}
        onReady={tileset => {
          console.log("onReady", tileset);
          ref.current.cesiumElement.zoomTo(tileset);
        }}
        onClick={(...args) => console.log("onClick", ...args)}
      />
  </Viewer>;
}
```

**Comment by nadavtal** [comment]
Further more, i see in the example 
https://resium.darwineducation.com/examples/?path=/story/cesium3dtileset--basic
that the tileset is not shown. perhaps it's the same issue?

**Comment by nadavtal** [comment]
i have tried all of them and none of the are fired. i thought it's becuase its not getting anything in the url field therefore they are not firing

**Comment by rot1024** [comment]
> Further more, i see in the example
> https://resium.darwineducation.com/examples/?path=/story/cesium3dtileset--basic
> that the tileset is not shown. perhaps it's the same issue?

It is because the json file of url is 404 not found. I'll fix it soon.

**Comment by nadavtal** [comment]
yes. i dont get the "Failed to load resource" if i put a wrong address in the url. i dont get anythink. hence the frustration:)

**Comment by nadavtal** [comment]
are you or do you know any experienced developers with resium than can help me when needed in my project? paid ofcoarse. i'm building a big project based on Cesium and Resium:)

**Comment by gavinhon** [comment]
@nadavtal you could try placing your 3dtiles under the 'public' folder. it works for me.

**Comment by rot1024** [comment]
If the issue persists, please reopen the issue.

**Comment by telmomm** [comment]
The issue persist for me with version 1.17.1, I try to put the json file in different locations and have the same problem (also with web json hosted files)
Any idea?
