### ISSUE TITLE
How to get the current camera orientation ?

### ISSUE THREAD

**Issue by bevikram** [darwin-education/resium#18]
Thank you for the awesome library, Can I Please have example on how to get the current camera orientation while playing on the globe ?

**Comment by rot1024** [comment]
Hi, you can get a Cesium's viewer object by accessing `cesiumElement` property of a reference of Viewer component. 

For example:

```jsx
import React from "react";
import { Viewer } from "cesium-react";
import { Math as CesiumMath } from "cesium";

class Example extends React.PureComponent {

  render() {
    return (
      <Viewer ref={e => { this.viewer = e; }}>
        <button onClick={this.inspectCamera}>Inspect camera</button>
       </Viewer>
     );
  }

  inspectCamera = () => {
    const cam = this.viewer.cesiumElement.scene.camera;
    console.log("position", cam.positionCartographic);
    console.log("heading (deg)", CesiumMath.toDegrees(cam.heading));
    console.log("pitch (deg)", CesiumMath.toDegrees(cam.pitch));
    console.log("roll (deg)", CesiumMath.toDegrees(cam.roll));
  }

}
```

I am working on writing a documentation including some tips such as this!

**Comment by bevikram** [comment]
Thanks a lot. I have just started working on react project which extensively uses cesium. Please let me know if I can help you document any of the features.
(I must tell you, the story book helped a lot in understanding this library)
