### ISSUE TITLE
Model destroy() not checking whether the context/primitiveCollection exists

### ISSUE THREAD

**Issue by chrisdirkisaurecon** [darwin-education/resium#189]
Having an issue when a Model element gets unmounted and unrendered. The error is:

`DeveloperError: This object was destroyed, i.e., destroy() was called.`

at Model.ts line 118 ( `context.primitiveCollection?.remove(element);` ):
```
  destroy(element, context) {
    context.primitiveCollection?.remove(element);
    if (!element.isDestroyed()) {
      element.destroy();
    }
  },
``` 

Presumably, this is because the context/primitiveCollectionn is already destroyed. ParticleSystem.ts seems to already check for this:
```
  destroy(element, context) {
    if (context.primitiveCollection && !context.primitiveCollection.isDestroyed) {
      context.primitiveCollection.remove(element);
    }
  },
```

I think the fix would be to add that check to Model.ts, and probably to check whether any other elements using primitiveCollection make that check too?

**Comment by rot1024** [comment]
Thank you for reporting. It has been fixed on 4333b1f7960327b40617c9955a79ab481749285c. Please wait a minute for releasing new version.

**Comment by chrisdirkisaurecon** [comment]
Hey, thanks for the fix! :)

Can you let me know when you think this will make it into a release?

**Comment by rot1024** [comment]
Sorry for the late release. I want to release new version after #184 is merged. The new version will be released at least later this week. If you are in a hurry, you can use the master branch.

**Comment by rot1024** [comment]
v1.10.1 is available now!
