### ISSUE TITLE
Hot Reload Breaks with Version 1.9.0

### ISSUE THREAD

**Issue by jhwohlgemuth** [darwin-education/resium#206]
# Description
After upgrading resium to latest version and updating my webpack config to work with new ESM version of CesiumJS, I noticed that the hot reload no longer functions like it used to.

# Example
If you change the color of an entity, the entity should update without changing the orientation of the globe (or anything else). After v1.8.1, any change with re-render the globe (even changes not associated with Cesium/resium). Basically, the globe flashes and everything is "reset" to initial visualization (with updated entities and stuff).

## Initial state
![initial](https://user-images.githubusercontent.com/6383605/72686123-e8a7ee80-3ab6-11ea-8045-238b35001902.PNG)

## Change globe orientation
![move](https://user-images.githubusercontent.com/6383605/72686119-e34aa400-3ab6-11ea-8eb9-f38957395a23.PNG)

## Post update entity color in code
> functional hot reload - this is what happens with resium v1.8.1 and below 😄 

![move_updated](https://user-images.githubusercontent.com/6383605/72686124-ecd40c00-3ab6-11ea-905f-ca62b1354ab3.PNG)

## Post update entity color in code
> new "reset" hot reload - this is what happens after resium v1.8.1 😞 

![move_updated_reset](https://user-images.githubusercontent.com/6383605/72686148-29076c80-3ab7-11ea-934b-51d5c1ed443d.PNG)

> The app I used for testing (with current versions and config) can be created using:
```bash
mkdir test-app && cd test-app
npx tomo-cli new app --use-react --with-cesium
```
> An example app with the pre-ESM version of CesiumJS can be found [here](https://github.com/jhwohlgemuth/demo-geolocation-react)

After a little detective work, I found that the issue manifests itself after v1.8.1. That is v1.8.1 has hot reload with previous function (with ESM and non-ESM versions of CesiumJS). Starting with v1.9.0, hot reload no longer works as it did (per description above) and in some cases fails to hot reload or refresh at all and instead presents a `this._view is undefined` error...

I step-updated all the associated dependencies and narrowed the issue down to resium. I was able to get my project to hot reload as desired using resium v1.8.1 with CesiumJS ^1.60.0 and ^1.65.0. Hot reload function was lost with both versions of CesiumJS with resium versions after v1.8.1. Code was tested with old versions of react, react-dom, and react-hot-reload.

I can try to provide more data if you need it and will help in any way I can. Any ideas from my description?

Keep up the great work! I love this project and ***reeeeeally*** want to use the current versions with hot reload as it once was :)

ありがとうございます！

**Comment by rot1024** [comment]
Thank you for reporting. I also tried about it.

- cesium v1.65.0 (latest) and resium v1.8.1: HMR works
- cesium v1.65.0 (latest) and resium v1.9.0-1.10.1: HMR does not work

resium v1.9.0 has many changes, using hooks. I will investigate further the cause of the issue.

**Comment by rot1024** [comment]
Workaround: put this code to `index.js` or `index.tsx`

```js
import { setConfig } from "react-hot-loader";

setConfig({ reloadHooks: false });
```

**Comment by jhwohlgemuth** [comment]
@rot1024 For the record, I verified that your workaround restores the desired HMR behavior (at least for my simple "dot color change" test). I will continue to use it and report back here.

Hopefully, finding a workaround means you have a lead on a "fix". Although, this workaround really is not so bad...

Is your plan to add this workaround to the docs and close this issue, or to restore the previous HMR behavior without the need for this workaround?

Either way, thanks for the great work! 😃

**Comment by rot1024** [comment]
I want to fix the cause fundamentally, but I'm busy right now so it will take some time.

**Comment by rot1024** [comment]
@jhwohlgemuth Hi, Resium v1.11.0 has been released, including fundamental resolution of the HMR bug. Please try it!

**Comment by jhwohlgemuth** [comment]
@rot1024 I have been using it for a few hours and it seems good to go. Thank you and keep up the great work!
