### ISSUE TITLE
User draw a polygon on the map

### ISSUE THREAD

**Issue by jduncanRadBlue** [darwin-education/resium#207]
Does anyone have an idea of how you could allow the user to draw a polygon on the map?  I have an app that has entities placed on the map and I'd like to allow the user to select an area on the map by drawing a polygon using their mouse and be able to filter out entities not in the polygon the user created.  Thanks in advance for any sample code you can offer me!

**Comment by rot1024** [comment]
1. You can get mouse position with Viewer.onClick
2. You can get location with #219
2. Draw entities with PointGraphics on clicked position (you can get with 2) to display points of the creating polygon
3. If any one of the point entities are clicked (Entity.onClick), you can draw polygon with PolygonGraphics.

**Comment by jduncanRadBlue** [comment]
@rot1024 I was able to get this working!  Thank you.  Now I ask, do you know how to find out if any point entities are inside the drawn polygon?  I need to remove any entities that are not within the drawn polygon....or at least change their color to note the filter.

**Comment by rot1024** [comment]
I don't know how to detect polygon and point intersection with Cesium, but you can use https://github.com/substack/point-in-polygon . or implement [ray casting algorithm](https://en.wikipedia.org/wiki/Point_in_polygon) yourself.
