### ISSUE TITLE
Can you ad 3D model / point cloud?

### ISSUE THREAD

**Issue by nickponline** [darwin-education/resium#21]
Is there an example or recommended way of using react-cesium to display a 3D model / pointcloud tileset?

**Comment by rot1024** [comment]
Components for 3D model and point cloud are now construction.

However `model` prop of Entity component is already available in the current version.

```
<Entity model={ModelGraphics} />
```

**Comment by rot1024** [comment]
Hi, I've released resium v1.0.0. You can use `<Cesium3DTileset>` and `<Model>`, `<ModelGraphics>` componet.

For details, refer to:
- [Cesium3DTileset documentation](https://resium.darwineducation.com/components/Cesium3DTileset)
- [Model documentation](https://resium.darwineducation.com/components/Model)
- [ModelGraphics example](https://github.com/darwin-education/resium/blob/master/src/stories/Entity.stories.tsx)
- [Cesium3DTileset example](https://github.com/darwin-education/resium/blob/master/src/stories/Cesium3DTileset.stories.tsx)
- [Model example](https://github.com/darwin-education/resium/blob/master/src/stories/Model.stories.tsx)
- [ModelGraphics example](https://github.com/darwin-education/resium/blob/master/src/stories/ModelGraphics.stories.tsx)
