### ISSUE TITLE
EntityDescription not working? 

### ISSUE THREAD

**Issue by siljec** [darwin-education/resium#222]
Hi,

I'm trying to add descriptions to some entities and followed some of the examples here: https://resium.darwineducation.com/examples/?path=/story/entity--basic 

(I'm using version 1.10.0 of resium)

When I try these examples, nothing happens when i click.
```
<Entity
          name="test1"
          position={Cartesian3.fromDegrees(-74, 40, 100)}
          point={{ pixelSize: 15, color: Color.YELLOW }}
          description="Normal Description"
/>
```
```
<Entity
          name="test2"
          position={Cartesian3.fromDegrees(-74, 30, 100)}
          point={{ pixelSize: 15, color: Color.BLUE }}>
          <EntityStaticDescription>
            <h1>Hello!</h1>
            <p>This is description. It can be described with static JSX!</p>
          </EntityStaticDescription>
</Entity>
```

when I try the example with EntityDescription:
```
 <Entity
                name="test3"
                position={Cartesian3.fromDegrees(-74, 20, 100)}
                point={{ pixelSize: 15, color: Color.RED }}>
                <EntityDescription>
                    <h1>Hello!</h1>
                    <p>This is description. It can be described with React!</p>
                </EntityDescription>
</Entity>
```

 i get the following error:
`Uncaught TypeError: Cannot read property 'frame' of undefined`

Not sure If I missed something and I'm using it wrong, or if it is a bug with resium?

**Comment by rot1024** [comment]
I think it's a bug. I will fix it.

**Comment by rot1024** [comment]
Did you forget using a Viewer component? or are you set a prop: infoox={false} ?

I tried but it works. Please provide the whole code to reproduce the issue.

**Comment by siljec** [comment]
Ah, I did have infobox={false}! Thank you for pointing that out for me! :D
