### ISSUE TITLE
billboard text label

### ISSUE THREAD

**Issue by NirAbel** [darwin-education/resium#243]
Hi,
how can i pick a billboard from my billboard collection (with mouse click) in resium and add a text form with all his details (speed, height and more..) next to my billboard.
i can't find any text form to add to my code that working for me.

thank you!
Nir

**Comment by rot1024** [comment]
An entity is recommended unless a number of the data is massive. It can have multiple visualizers: e.g. point, label, billboard.

```tsx
<Entity position={...} onClick={...}>
  <BillboradGraphics ... />
  <LabelGraphics ... />
</Entity>
```

**Comment by NirAbel** [comment]
thank you but i'm not sure how to use it.
i have drones component, they are from billboard.
i want to click with my mouth on my billboard and to get new form window with all the information that i choose to add to my form.
i can't find example to BillboardGraphics this is the solution for my problem?
can you give me an example for how to write it?
thank you very much!
Nir

**Comment by rot1024** [comment]
Here is example of graphics:

https://resium.darwineducation.com/examples/?path=/story/entity--graphics

Please open "story" tab and you can refer to example codes.

**Comment by NirAbel** [comment]
amazing thank you!
is it possible to make the LableGraphics to show on click and disappear with another one (on the billboard)?
thank you!!

**Comment by rot1024** [comment]
If you are familiar with React, it may be easy.

```jsx
const Component = ({ entities }) => {
  const [labelDisplayedEntity, setLabelDisplayedEntity] = useState();
  return (
    <Viewer>
      {entities.map(e => {
        <Entity
          key={e.id} 
          id={e.id}
          position={e.position}
          onClick={() => setLabelDisplayedEntity(e.id)}>
          <BillboardGraphics ... />
          <LabelGraphics show={labelDisplayedEntity === e.id} ... />
        </Entity>
      }}
    </Viewer>
  );
};
```
