### ISSUE TITLE
Cesium Api Key Getting 401 Unauthorized

### ISSUE THREAD

**Issue by TeddyShang** [darwin-education/resium#265]
The default key when calling api.cesium.com/vi/assets/2/endpoint?access_token={access_token}  is throwing a 401 unauthorized for every Cesium Ion map imagery selection. What the best one to supply our own token when working with Resium?

**Comment by rot1024** [comment]
Please upgrade cesium to the latest version because the default API key is changed by Cesium team. The default API key of cesium older than before three version will be deprecated. Or register your account to Cesium Ion and use your API key.
