### ISSUE TITLE
PolylineCollection & polyline details

### ISSUE THREAD

**Issue by NirAbel** [darwin-education/resium#266]
Hello,
I'm looking for an option to add more details to my Polylines.
I want to add the height of the polyline and to add number of the polyline inside the PolylineCollection. (that the user will undersatnd the flow of the path- where it's begin and where it's end).
there is an solution for that with Resium?
thank you!
Nir

attaching example for what i want to build: 
![mission planner example](https://user-images.githubusercontent.com/19760193/75988138-cef12800-5ef9-11ea-9e15-0d3335c226e8.PNG)

**Comment by rot1024** [comment]
You can use LabelCollection and Label component, or I recommend to use Entity instead of PoylineCollection.

```js
const Component = ({ points }) => {
  return (
    <Viewer>
      {points.map((p, i) => (
        <Entity key={i} position={p}>
          {i > 0 && <PolylineGraphics positions={[points[i - 1], p]} />}
          <LabelGraphics text={i} />
        </Entity>
      ))}
    </Viewer>
  );
}
```

**Comment by NirAbel** [comment]
thank you!
is it possible to drag an Entity point with a mouse?
i want to drag Entity with my mouse from one position to other position.
thank you again!
Nir

**Comment by rot1024** [comment]
Maybe yes, but Cesium does not have entity drag-n-drop function, so you have to implement it by yourself.
