### ISSUE TITLE
Cesium is undefined

### ISSUE THREAD

**Issue by smonikantara** [darwin-education/resium#267]
`import Cesium from 'cesium'` returns `undefined`

I am using:
- React v16.8.6
- Resium v1.11.0
- Cesium v1.65
- @types/cesium v1.65.3

Similar to #126 

Thanks.

**Comment by rot1024** [comment]
default export of Cesium are deleted since Cesium v1.63.

```js
import Cesium from "cesium"; // not work

import { Viewer } from "cesium"; // work
```

**Comment by smonikantara** [comment]
Thank you for the quick response.
