### ISSUE TITLE
BillboardGraphics & Polyline color

### ISSUE THREAD

**Issue by NirAbel** [darwin-education/resium#286]
hello,
i'm trying to find an option to change my BillboardGraphics png icon color & Polyline color how can i do it?
when i'm trying to do this one: 
BillboardGraphics
              className="back"
              image={end}
              color={Color.RED}
              fillColor={Color.RED}
              scale={0.03}

it's not working and i can't see any red color.
also in my Polyline (it's only white line).

thank you!
Nir

**Comment by rot1024** [comment]
Please refer to documentation and examples to learn about how to use: https://resium.darwineducation.com/examples/?path=/story/entity--graphics
