### ISSUE TITLE
PointPrimitiveCollection event on rigth click

### ISSUE THREAD

**Issue by awaska** [darwin-education/resium#287]
hi, i need to add an event to the point, i need it because when i click the point with (id,lat,long)  it has  to run a function to display a list, i have a lot of points. how can i do it ? on the story board do this:

`import { hot } from "react-hot-loader/root"
import React from "react"
import { Viewer,Entity,PointPrimitive, PointPrimitiveCollection } from "resium"
import { Cartesian3, Color, Transforms} from "cesium";

function GloboComponente (props){
	const center = Cartesian3.fromDegrees(-75.59777, 40.03883);
	return(
		<div>
		<Viewer full>
      <PointPrimitiveCollection modelMatrix={Transforms.eastNorthUpToFixedFrame(center)}>
        <PointPrimitive
          color={Color.ORANGE}
          position={new Cartesian3(0.0, 0.0, 0.0)}
          onClick={console.log("onClick")}
          onDoubleClick={console.log("onDoubleClick")}
          onMouseDown={console.log("onMouseDown")}
          onMouseUp={console.log("onMouseUp")}
          onMiddleClick={console.log("onMiddleClick")}
          onMiddleDown={console.log("onMiddleDown")}
          onMiddleUp={console.log("onMiddleUp")}
          onMouseMove={console.log("onMouseMove")}
          onPinchEnd={console.log("onPinchEnd")}
          onPinchMove={console.log("onPinchMove")}
          onPinchStart={console.log("onPinchStart")}
          onRightClick={console.log("onRightClick")}
          onRightDown={console.log("onRightDown")}
          onRightUp={console.log("onRightUp")}
          onMouseEnter={console.log("onMouseEnter")}
          onMouseLeave={console.log("onMouseLeave")}
        />
      </PointPrimitiveCollection>
    </Viewer>
		</div>
		)
}
export default hot(GloboComponente)`
but it dose not work

**Comment by rot1024** [comment]
Please refer to [documentation](https://resium.darwineducation.com) and examples to learn about how to use. You have to wrap components with Viewer component.
