### ISSUE TITLE
undefined imports in tests

### ISSUE THREAD

**Issue by chriswingler** [darwin-education/resium#34]
Hi, I've been trying to add a `Billboard.test.tsx`, but I keep getting various undefined errors with imports, such as:

```
import { Cartesian3 } from 'cesium'

const center = Cartesian3.fromDegrees(-75.59777, 40.03883);

console.log(center);
```

will produce `TypeError: Cannot read property 'fromDegrees' of undefined`

Anyone know what's going on here?

This code works in `src/stories/Billboard.stories.tsx`.

**Comment by rot1024** [comment]
Cesium cannot be loaded in jest env because Cesium deeply depends on Web APIs (WebWorker, WebGL and so on...)

So we have to create mocks for Cesium objects. Please add new mock to __mocks__ directory.

**Comment by chriswingler** [comment]
Ahh great, thank you!
