### ISSUE TITLE
LabelGraphics over each other

### ISSUE THREAD

**Issue by NirAbel** [darwin-education/resium#371]
hello,
i am using LabelGraphics to display information and sometimes i have a problem that two LabelGraphics are over each other and i can't see the information.
there is a solution to avoid two different Entity to be over other Entity?
i'm attaching a picture for example.
there is maybe hover option for Entity? (that i will see him just when my mouth is above him).
thank you!
Nir
![Untitled](https://user-images.githubusercontent.com/19760193/81538500-7d40a000-9377-11ea-897e-1f0d8805e956.png)

**Comment by rot1024** [comment]
Entity can have only one Graphics component, so you are right. Two different entities are needed.
