### ISSUE TITLE
Unable to start storybook on v1.0.0-beta.1

### ISSUE THREAD

**Issue by symmetriccurve** [darwin-education/resium#38]
ERROR in /Users/user/projects/resium/src/core/CesiumComponent.tsx(71,36)

 TS7017: Element implicitly has an 'any' type because type 'Readonly<WithContextProps<P, C>> & Readonly<{ children?: ReactNode; }>' has no index signature.

**Comment by rot1024** [comment]
Hi, thank you for your reporting.

But I could not reproduce the error. Are you using the latest node and yarn?

```sh
git clone https://github.com/darwin-education/resium.git
cd reisum
git checkout v1.0.0-beta.1
yarn
yarn storybook
```

**Comment by symmetriccurve** [comment]
Thank you @rot1024.
