### ISSUE TITLE
How to turn WebMapServiceImageryProvider into Layer and Deployment

### ISSUE THREAD

**Issue by KritTangcharoenkijkul** [darwin-education/resium#398]
Hi there,

Currently, I am doing Web Map Service Imagery Provider to display  WMS on the map. I managed to do it. 

![image](https://user-images.githubusercontent.com/48550332/83650059-1c0c9500-a5e2-11ea-8e07-edaece57a498.png)

However, I want to make it into an Imagery Layer similarly to this picture. By adding layer allowing them to be shown or not shown in form of layer.

![image](https://user-images.githubusercontent.com/48550332/83650335-6f7ee300-a5e2-11ea-8025-73022800c95d.png)

The code that I use is as follow

import React from "react";
import { Viewer,  ImageryLayer } from "resium";
import {  WebMapServiceImageryProvider } from "cesium";

const App = () => (

  <Viewer>
    <ImageryLayer
      imageryProvider={ 
        new WebMapServiceImageryProvider({
          url : 'http://localhost:8080/geoserver/wms',
          layers : 'WaterLevelSystem:data_logger_model',
          proxy : 'http://localhost:8080/geoserver/wms',
          style: "default",
          tileMatrixSetID: "250m",
          maximumLevel: 5,
          parameters: {
            transparent : true,
            tiled : true,
            format : 'image/png'
          },
        })
      }
  </Viewer>
);
export default App;
 

Also, I have tried deploying the Resium result on the web for few days. However, today, the Earth disappears. However, the icon is still there. Is it because of licensing or its just glitches out?

![image](https://user-images.githubusercontent.com/48550332/83650873-0c418080-a5e3-11ea-8083-c97999cf8592.png)

Thank you

**Comment by rot1024** [comment]
```
import React from "react";
import { Viewer, ImageryLayer } from "resium";
import { WebMapServiceImageryProvider } from "cesium";

const App = () => (

); export default App;
```

Please provide code inside App component so that I know details.
