### ISSUE TITLE
Polyline Color

### ISSUE THREAD

**Issue by NirAbel** [darwin-education/resium#399]
hello,
Is it possible to change Polyline Color (inside PolylineCollection)?
example code: 
<PolylineCollection>
                {
                    props.polylinePositions.map((curr, index) =>
                        <Polyline
                            positions={curr}
                            width={4}
                        />
                    )
                }
</PolylineCollection>

thank you!
Nir

**Comment by rot1024** [comment]
You can change color with `material` prop of Polyline component, but I recommend to use Entity and PolylineGraphics component instead of Polyline and PolylineCollection.
