### ISSUE TITLE
Scene Picker

### ISSUE THREAD

**Issue by peteratkinson** [darwin-education/resium#4]
How would one go about implementing this? 

`var pickedFeature = viewer.scene.pick(movement.position);`

Can't seem to see anywhere in the source (inside of Scene.js), that uses the pick function.

Has this been implemented? I'm presuming this is to be done? (EntityCollection maybe?)

I'd be happy to contribute to this.

**Comment by rot1024** [comment]
You can access `Viewer` object with `cesiumComponent` property in the components. It is available by using `ref` prop on Viewer component.

```js
class App extends React.PureComponent {

  render() {
    return (
      <Viewer ref={ref => { this.viewerComponent = ref; }}>
        <ScreenSpaceEventHandler useDefault>
          <ScreenSpaceEvent action={this.mouseEvent} type={ScreenSpaceEventType.MOUSE_MOVE} />
        </ScreenSpaceEventHandler>
       </Viewer>
    );
  }

  mouseEvent = e => {
    const picked = this.viewerComponent.cesiumComponent.scene.pick(e.endPosition);
    const id = picked ? picked.id || picked.primitive.id : null;
    if (picked && id instanceof Entity) {
       // picked is the picked entity
    }
  };

}
```

`cesiumComponent` is undocumented now. I plan to prepare the documentation.

**Comment by shortwavedave** [comment]
I think this may still be an issue, and if the viewer is wrapped by another component then this method doesn't seem to work

**Comment by rot1024** [comment]
Hmm but I think that is limitation of React's design. React's components don't have methods. If we want to use them, we have to use ref. For example: "focus" method of `<input>` component.

Anyone wraps a Resium component needs to use `forwardRef` to allow access to Cesium's elements.

related: https://ja.reactjs.org/docs/forwarding-refs.html

**Comment by shortwavedave** [comment]
You're right, this is a react thing. The ref needs to be in the top level component that is returned by the exported class. Considering this your example works fine. Thanks!
