### ISSUE TITLE
Building a React Component with a Resium Component

### ISSUE THREAD

**Issue by lintaonz** [darwin-education/resium#410]
Hi, 

I try to build a Map component on top of the Resium component. So that I can use my Map component as a package in my main app.

I read this [article](https://medium.com/traversals-tech-blog/building-a-react-library-with-a-cesium-component-cac19175f7cb) and try to make it work with my sample app with this example [component](https://github.com/traversals-analytics-and-intelligence/example-react-cesium-library). 

When I start my sample app, I got follow error - https://reactjs.org/docs/error-decoder.html/?invariant=321

It seems Resium **v1.11.0** hooks not working well if I try to use it as an external package. 

If I downgrade the Resium as **v1.5.0** which doesn't use React Hooks. Everything works fine.

Here is my example [project](https://github.com/lintaonz/my-app/commit/22fb0f1710b3901255dacb36aa3dc0e7067dc7f5).  Could someone tell how to fix this issue, please?

Thanks,

Tao

**Comment by theErikss0n** [comment]
I have the same issue. 
Steps to reproduce:
1. Clone this repo
2. Create a different react repo and include resium as a local dependency
3. Import and use viewer from resium

This error appears:
![2020-06-19_15061592574790](https://user-images.githubusercontent.com/38251684/85141693-71ce7780-b247-11ea-9eb6-1a40e92bad0e.png)
![2020-06-19_15061592574795](https://user-images.githubusercontent.com/38251684/85141696-73983b00-b247-11ea-9d39-bf41bb9e4193.png)

When I add resium as dependency from npm itself, everything works.
It seems that something in the local buildchain is different than the production build and results in the error.

**Comment by Etheryte** [comment]
Running into the same problem, looks like it's a packaging problem? It seems like React is ending up in the bundle a number of times for some weird reason.

**Comment by lintaonz** [comment]
We found out the issue was caused by the container package. Basically, our app has the following structure: 
App (React-dom) -> Map component (Resium with React-dom). 

You can see we have two copies of React-dom here. To solve this, I have to exclude the Map component's React-dom from WebPack. Here is my WebPack config. 

Hope this help.

```javascript
const cesiumSource = 'node_modules/cesium/Source';
const cesiumWorkers = '../Build/Cesium/Workers';
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'index.js',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'src'),
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }]
      },
      {
        test: /\.(png|gif|jpg|jpeg|svg|xml|json)$/,
        use: ['url-loader']
      }
    ]
  },
  performance: {
    hints: false
  },
  plugins: [
    new CopyWebpackPlugin({
      patterns: [
        {
          from: path.join(cesiumSource, cesiumWorkers),
          to: 'Workers'
        },
        {
          from: path.join(cesiumSource, 'Assets'),
          to: 'Assets'
        },
        {
          from: path.join(cesiumSource, 'Widgets'),
          to: 'Widgets'
        }
      ]
    }),
    new webpack.DefinePlugin({
      CESIUM_BASE_URL: JSON.stringify('/')
    })
  ],
  resolve: {
    alias: {
      cesium$: 'cesium/Cesium',
      cesium: 'cesium/Source'
    }
  },
  target: 'node',
  externals: {
    antd: 'antd',
    react: {
      commonjs: 'react',
      commonjs2: 'react',
      amd: 'React',
      root: 'React'
    },
    'react-dom': {
      commonjs: 'react-dom',
      commonjs2: 'react-dom',
      amd: 'ReactDOM',
      root: 'ReactDOM'
    }
  }
};
```

**Comment by Etheryte** [comment]
I don't think this issue should be closed as at the end of the day this is an issue with Resium's packaging. Resium should **not** include react-dom directly in its bundle.

**Comment by rot1024** [comment]
Did you try latest version of Resium? Resium does not contain react, react-dom, and cesium.

**Comment by rot1024** [comment]
I guess this problem is due to cesium-react-library, because cesium-react-library does not exclude external libraries on build with webpack, so there are mixed different versions of React. I think cesium-react-library should exclude external libraries with `externals` in webpack config.
