### ISSUE TITLE
Type 'Cartesian3' is not assignable to type 'Cartesian3 | Rectangle'

### ISSUE THREAD

**Issue by makeupsomething** [darwin-education/resium#419]
Im not sure what I'm doing wrong here. But I get a type error

`Type 'Cartesian3' is not assignable to type 'Cartesian3 | Rectangle'.
  Type 'Cartesian3' is missing the following properties from type 'Cartesian3': isConstant, definitionChanged, referenceFrame, getValue, getValueInReferenceFrame  TS2322`

```jsx
<CameraFlyTo
 duration={1}
  destination={Cartesian3.fromDegrees(
   35.133188,
   138.7802198,
   1100,
  )}
 once={true}
/>
```

**Comment by rot1024** [comment]
Thank you for reporting. It is fixed in v1.12.0. Please try it and reopen this issue if the issue persists.
