### ISSUE TITLE
Createa a polygon with Resium picking up the coordinates from the map

### ISSUE THREAD

**Issue by anmobor** [darwin-education/resium#422]
I want to create a polygon over the map picking the coordinates from the map. I tried to create points with Entities and I am able, but I can't with polygon. Please may anyone create a polygon picking the coordinates from the map. Later I will need to do the same with polylines.

Thank you in advance

**Comment by panpn** [comment]
Does the example here help? https://github.com/darwin-education/resium/issues/219
