### ISSUE TITLE
ref created for <Entity> shows undefined

### ISSUE THREAD

**Issue by ajiteshchhatani** [darwin-education/resium#424]
I am working with resium <Viewer> and <Entity> elements and want to zoomTo a bunch of <Entity>s after the 2D Scene has been loaded in the viewer. For that, I have created refs for both <Viewer> and <Entity>. However, the ref created for <Entity> remains undefined and hence i have no way to ref to <Entity> and zoom to it.

I went through the documentation and found this 
*Note: cesiumElement property in the ref object can be undefined: e.g. when an initialization error is occurred. Please check if it's not undefined when using cesiumElement.*

Any idea how we can fix the above initialization error?

Resium Version used: 1.12.0

Code as below:

    import React, { useState, useRef, useEffect } from 'react';
    import { Cartesian3, SceneMode, IonImageryProvider } from 'cesium';
    import { BillboardGraphics, Camera, Entity, Viewer } from 'resium';

    const dummyElement = document.createElement('div');

    function AssetMap(props) {
    const [billboardClicked, setBillboardClicked] = useState(false);
    const [selectedEntity, setSelectedEntity] = useState({});
    
    const ref = useRef(null);  // Ref for <Viewer>
    const entityRef = useRef({}); //Ref for <Entity>

    const options = {
    animation: false,
    baseLayerPicker: false,
    fullscreenButton: false,
    geocoder: false,
    homeButton: false,
    selectionIndicator: false,
    timeline: false,
    navigationHelpButton: false,
    navigationInstructionsInitiallyVisible: false,
    scene3DOnly: true,
    infoBox: false,
    sceneMode: SceneMode.SCENE2D,
    creditContainer: dummyElement
    };

    useEffect(() => {
      // checking if viewer ref.current.cesiumElement is not undefined
      if(ref.current && ref.current?.cesiumElement){
        //Want to zoom to a collection of entities but the entityRef.current.cesiumElement remains undefined
        ref.current.cesiumElement.zoomTo(entityRef.current.cesiumElement);
      }
    }

    return(
    <>
    <Viewer {...options} ref={ref}>
      //props.data includes results from api call from which we construct <Entity> markers
      {props.data.map(item => (
      <Entity
            id={item.id}
            key={item.id}
            show={item.showMarker}
            position={Cartesian3.fromDegrees(item.longitude, item.latitude)}
            onClick={onBillboardClick}
            ref={entityRef}>
      <BillboardGraphics image={item.assetMarker} />
      </Entity>
      ))}
    </Viewer>
    </>
    )

    }
    export default AssetMap

The problem seems to be <Entity> ref being undefined

All I am looking for is to use the viewer.zoomTo() api to zoom to a bunch of entities and hence using a entityRef seemed to be the only solution.

Any help would be greatly appreciated with this issue.

Let me know in case I have missed out any details.

**Comment by ajiteshchhatani** [comment]
@rot1024 can you please help with the above?

**Comment by rot1024** [comment]
I think there is no problem with your code. Try the latest version of Resium and reopen this issue if the problem persists.
