### ISSUE TITLE
CameraFlyTo and  Scene mode

### ISSUE THREAD

**Issue by djangoliv** [darwin-education/resium#426]
I try to setting default location at beginning in 2D mode but it doesn't works:

```
return (
    <Viewer full>
      <Scene mode={SceneMode.SCENE2D} />
      <CameraFlyTo
        duration={0}
        destination={Cartesian3.fromDegrees(-15, 85, 100000)}
        once={true}
      />
    </Viewer>
  );
}
```

This code works without the `Scene` parameter `mode={SceneMode.SCENE2D}`

It also works at click event without the `once={true}` (but not at beginning)

"resium": "^1.12.0"

Regards

**Comment by rot1024** [comment]
Try the latest version of Resium and reopen if the issue persists.
