### ISSUE TITLE
ScreenSpaceEvent Cartesian2 object giving strange values when converted using Cartographic.fromCartesian.

### ISSUE THREAD

**Issue by sstephans** [darwin-education/resium#434]
I'm taking the event from `ScreenSpaceEvent` and covnerting it's Cartesian2 position property to Cartesian3 like so

`const cartesianConverted = new Cartesian3(e.position.x, e.position.y);`

which gels with the Cesium docs usage on how to create a Cartesian3 (and according to my debugger, it does create it and transfer the x and y values accurately.)

Then I want to get the lat/long values so I do

`const cartoConverted = Cartographic.fromCartesian(cartesianConverted)`

which according to the Cesium docs takes a Cartesian3 as the only required argument. However, the generated object always shows 0 for latitude, and longitude seems to vary with the delta y of the mouseclicks, which seems backwards. Height I can't tell if it's varying with the delta x or if it's doing something else strange. 

I'm having a hard time pinpointing where the wrong behavior is coming from. The Cartographic seems to work when doing other things, so I suspect it's something to do with the way that the `ScreenSpaceEvent` is grabbing and giving me x and y coords? There is no `ScreenSpaceEvent` in the Cesium docs so I'm not sure how to check if it behaves how the CesiumJS classes are expecting.... 

any ideas what's up?

**Comment by rot1024** [comment]
You can use `Camera#pickEllipsoid` method to convert window position into Cartesian3 on the Earth.

**Comment by sstephans** [comment]
Thanks, I'll try that. Can you help me out with the usage syntax? I see in the docs there's this example

```
args => (
  <Viewer full>
    <Camera {...args} {...actions("onMoveEnd", "onMoveStart", "onChange")} />
    <CameraFlyTo duration={5} destination={Cartesian3.fromDegrees(139.767052, 35.681167, 100)} />
  </Viewer>
)
```

but I'm not sure how I'd use the method. Something like `<Camera {action("pickEllipsoid(Cartesian3")} />` ??

**Comment by rot1024** [comment]
Get and use Cesium's raw object by ref. For details, refer to [the documentation](https://resium.darwineducation.com/guide#accessing-to-a-raw-cesiums-element).
