### ISSUE TITLE
What does "delta" parameter of the onWheel from viewer denote

### ISSUE THREAD

**Issue by pulli23** [darwin-education/resium#435]
Well in our application we wish to keep track of the camera position while the user pans/scrolls around. One of the inputs is the "scroll wheel" event. This event zooms in (lowers) camera and vice versa.

The documentation, however, is quite meager: https://resium.darwineducation.com/components/Viewer 

    onWheel | (delta: number) => void

I do see that delta is the based on the direction of movement, but what does the value denote.. The actual change in Z-position of the camera? If I subtract the value from the camera and reset the camera to that position I do notice the camera isn't at the same position as it would've been after scrolling. - When zooming in/going down I notice the change in number is smaller than the actual visual change.

So what does it mean?

**Comment by rot1024** [comment]
Resium is a just wrapper of Cesium. So please contact to Cesium team.
