### ISSUE TITLE
EntityDescription doesn't render

### ISSUE THREAD

**Issue by jbrandli** [darwin-education/resium#436]
EntityDescription does not render anything. It doesn't work in the resium storybook example page, but this issue also happens for me no matter how complex or simple the JSX inside the EntityDescription component.

https://resium.darwineducation.com/examples/?path=/story/entity--description

**Comment by rot1024** [comment]
Now I am investigating it.

**Comment by rot1024** [comment]
I fixed it now. The issue is due to changes in Cesium side. I'll release a new version soon.

**Comment by rot1024** [comment]
v1.13.1 has been released. Please try it and reopen this issue if the issue persists.

**Comment by jbrandli** [comment]
It works sometimes now, but its not consistent. Sometimes i click an entity and it shows the infobox but not the description. If click several different entities eventually it will work.

**Comment by rot1024** [comment]
I know it but EntityDescription works by overwriting Cesium's infobox function, so it is not stable. This problem seems to occur particularly when we use together EntityDescription, EntityStaticDescription, and description props of the entities.

**Comment by otaviobps** [comment]
Is this fixed?

I'm trying to use the `EntityDescription` but the description only renders if I click on an `Entity` then I click on another `Entity`. The second one renders fine:

![image](https://user-images.githubusercontent.com/28715087/106137523-97aaeb80-6149-11eb-8883-4f8f34c5ae6b.png)
First click only renders the infobox and the title

![image](https://user-images.githubusercontent.com/28715087/106137597-abeee880-6149-11eb-9727-782e002fddda.png)
Second click renders the description

The description only renders if I click on the second entity without closing the infobox.

Here is the code:

```
{data.map((node) => {
        if (node.lat && node.lng) {
          return (
            <Entity
              key={node.publicKey}
              point={{
                color: Color.fromCssColorString(node.color),
                pixelSize: 8,
              }}
              position={Cartesian3.fromDegrees(node.lng, node.lat)}
            >
              <EntityDescription>
                <Typography>Test</Typography>
              </EntityDescription>
            </Entity>
          );
        }
        return null;
      })}
```
