### ISSUE TITLE
Nothing was returned from render when trying to use any graphics wrapped in an Entity

### ISSUE THREAD

**Issue by jabusir** [darwin-education/resium#438]
When I pass "point" to Entity, I can get a circular point rendering on the globe as expected, but as soon as I wrap any Graphic component with Entity, the app crashes with this error:

![image](https://user-images.githubusercontent.com/29559541/94624765-0e9fa880-026c-11eb-8267-ea565f698dee.png)

All the code is on the same level, and there isn't any custom data. 
```
import React, { useState, useEffect } from "react";
import { hot } from "react-hot-loader/root";
import { Cartesian3, Color } from "cesium";
import { Viewer, Entity, BoxGraphics } from "resium";

import "./App.css";

function App() {
  return (
    <Viewer full>
      <Entity
        name="BoxGraphics"
        description="BoxGraphics!!"
        position={Cartesian3.fromDegrees(0, 0, 0)}
      >
        <BoxGraphics
          material={Color.RED}
          dimensions={new Cartesian3(400000.0, 300000.0, 500000.0)}
        />
      </Entity>
    </Viewer>
  );
}

export default hot(App);


```

Has anyone encountered this bug before, and can refer to me to any resources that might be of help? Thanks

**Comment by rot1024** [comment]
What Cesium and Resium's version are you using?

**Comment by jabusir** [comment]
hi rot @rot1024, 

I'm using:
cesium 1.73.0
resium 1.13.0
craco-cesium 1.2.0

**Comment by rot1024** [comment]
I tried to update the example project in the Resium repository as following:

`app.js`

```jsx
import React from "react";
import { Cartesian3, Color } from "cesium";
import { Viewer, Entity, BoxGraphics } from "resium";

function App() {
  return (
    <Viewer full>
      <Entity
        name="BoxGraphics"
        description="BoxGraphics!!"
        position={Cartesian3.fromDegrees(0, 0, 0)}
      >
        <BoxGraphics
          material={Color.RED}
          dimensions={new Cartesian3(400000.0, 300000.0, 500000.0)}
        />
      </Entity>
    </Viewer>
  );
}

export default App;
```

And then it works well:

![localhost_3000_](https://user-images.githubusercontent.com/3888696/94633324-e49bc400-0307-11eb-876e-8d696e7bed20.png)

So that issue may be due to your environment. If you use yarn, try to delete yarn.lock and reinstalling modules.

**Comment by rot1024** [comment]
Also I tried it at https://github.com/rot1024/create-react-app-cesium-example and I found the issue. So I guess the issue occurs only in the CRA environment. I am investigating it...

![image](https://user-images.githubusercontent.com/3888696/94634143-37767b00-030a-11eb-8ca1-a9b410c6a25e.png)

**Comment by rot1024** [comment]
I found there is a bug in Resium. I will fix it soon and release a new version. Thank you!

**Comment by rot1024** [comment]
v1.13.1 has been released! Try it!

**Comment by jabusir** [comment]
Wow, thank you! Very much appreciated :)
