### ISSUE TITLE
How to add a div element for an entity or billboard marker so that when marker clicked it should display as an overlay on top 

### ISSUE THREAD

**Issue by aneesha2890** [darwin-education/resium#441]
So when creating an entity and passing description or creating a marker , I want that the div should be displayed on top of the marker as an overlay rather than sliding on the top left . How can we do it????
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/32732884/95198201-75870980-07f8-11eb-9bf0-680c2aee0134.png)

**Comment by aneesha2890** [comment]
Please can someone help.. this is an urgent need and I am unable to proceed further

**Comment by rot1024** [comment]
Very simple example:

```js
export default function Component() {
  const viewer; = useRef(null);
  const [shown, setShown] = useState(false);

  return (
    <Viewer onSelectedEntityChange ={() => setShown(!!viewer.current?.cesiumElement?.selectedEntity)}>
      <Entity position=[/* omitted */} />
      <div style={{ style: shown ? "block" : "none", position: "absolute", top: 0, left: 0 }}>
        Hello
      </div>
    </Viewer>
  );
}
```

**Comment by aneesha2890** [comment]
Hello @rot1024  thank you, it worked but how do I find the location of where the marker is , usually we pass the latitude,longitude details, but to show the overlay, I might need exact location of the marker. How to get that?
![image](https://user-images.githubusercontent.com/32732884/96722909-85dbde80-13cb-11eb-8add-22186c365dd2.png)

**Comment by rot1024** [comment]
`entity.position.getValue()` works. This is about the usage of Cesium, not Resium. Refer https://cesium.com/docs/cesiumjs-ref-doc/Entity.html?classFilter=entity#position
