### ISSUE TITLE
Is there a way to make the Viewer default to the tilted flat version of the globe?

### ISSUE THREAD

**Issue by jabusir** [darwin-education/resium#442]
Can I configure default settings in the code for when the Viewer renders versus having to select them from the drop down in the top right corner once the globe is rendered?

Thanks :)

**Comment by jabusir** [comment]
As well as selecting a default texture option

**Comment by rot1024** [comment]
What does "the tilted flat version" mean?

**Comment by jabusir** [comment]
haha apologies. Thanks for your response. I guess I got caught up in my own jargon. 

When the viewer renders, it has a toolbar in the top right corner. One of these options changes the Globe from the default spherical globe to a 2D/flat map that cannot be tilted or rotated, and a third option of a 2D/flat map that can be tilted and rotated. 
![image](https://user-images.githubusercontent.com/29559541/96179130-3ede7c80-0ee5-11eb-99ea-833443fa9614.png)

Is there anyway to set one of these options as the default instead of the spherical globe? 


Additionally, how can I have the globe texture default to the ESRI World Map texture?

Thank you

**Comment by Shadowru** [comment]
let esri = new Cesium.ArcGisMapServerImageryProvider({
    url : 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer'
});

<Viewer  imageryProvider = {esri} sceneMode={Cesium.SceneMode.SCENE2D} mapProjection={new Cesium.WebMercatorProjection()}>

**Comment by jabusir** [comment]
Oh wow that's really helpful. 

Thank you so much @Shadowru
