### ISSUE TITLE
Rendering a large amount of entity points.

### ISSUE THREAD

**Issue by green1971weekend** [darwin-education/resium#443]
I've really stuck on that mission and need help please. I need to render a huge amount of entities and if I render about 20-30 entities it renders very well. The problem starts when amount of entities becomes more. I'm relatively new in react and ask to not judge strictly. 

My code for render method: 

    render() {
        const entityList = this.state.data;
        let result;
        
        if(entityList.length !== 0)
        {
            result = entityList.map((value, index) => {
                return( 
                    <Entity key={index} position={Cartesian3.fromDegrees(parseFloat(value.Longitude), parseFloat(value.Latitude))}>
                        <PointGraphics pixelSize={10} />
                        <EntityDescription>
                            <h1>{value.Name}</h1>
                            <p>Year: {value.Year} Amount: {value.Amount}</p>
                        </EntityDescription>
                    </Entity> 
                );
            });
        }
        
        return (
            <Viewer>
                {result}
            </Viewer>
        );  
    }

**Comment by rot1024** [comment]
Entity is not suitable for displaying large amounts of data. I recommend using PointPrimitive and PointPrimitiveCollection.

**Comment by green1971weekend** [comment]
Thanks for that fastest answer! Yes with PointPrimitive and PointPrimitiveCollection large amount renders well. But can you give some advise about what to do with description to each of this points?

**Comment by rot1024** [comment]
Displaying description is only supported for Entity, so we have to implement the logic to display the description for each point primitives, but we can it.

```jsx
<Viewer onClick={e => {
  if (e instanceof PointPrimitive) {
    // ...
  }
}}>
  {/* ... */}
</Viewer>
```

**Comment by green1971weekend** [comment]
Unfortunately when I'm trying to click on point the following error occurs: 
TypeError: Right-hand side of 'instanceof' is not callable

**Comment by green1971weekend** [comment]
Instead of attach handler to Viewer component I'm attaching it to each PointPrimitive  and assign some data to only string _id property... without checking for instance. It works well. Thanks for advise!
