### ISSUE TITLE
Supporting Camera.DEFAULT_VIEW_RECTANGLE

### ISSUE THREAD

**Issue by MrShtrahman** [darwin-education/resium#455]
Hi there!

I would like to configure my "home" default value, so that when I click on the Cesium default "home" button, I could "fly" to a desired rectangle.

If `Camera.DEFAULT_VIEW_RECTANGLE` is not supported, is there any other way to do so?

I suppose that trying `<CameraFlyHome />` won't do the trick...

Thanks in advance :)

**Comment by rot1024** [comment]
That issue seems not to be related because Resium is just a wrapper of Cesium. CameraFlyHome component just calls `camera.flyHome()`.
