### ISSUE TITLE
How to adjust the frustum of CameraFlyTo?

### ISSUE THREAD

**Issue by jabusir** [darwin-education/resium#466]
I've been trying to get the camera to not be directly above the map, but hover over at an angle. 

How can I set the frustum or angle on the CameraFlyTo? Do I need to add a Camera component?

**Comment by rot1024** [comment]
You can change frustum with Camera component, but we cannot change it with CameraFlyXXX components. It is due to Cesium's API.

```jsx
<Camera frustum={new PerspectiveFrustum({ fov: /* ... */ })} />
```

**Comment by jabusir** [comment]
Ok great. I'll try that out thanks for responding. Will also look more into cesium' documentation.
