### ISSUE TITLE
Country/city labels on the background are improportional when zoomed into an area

### ISSUE THREAD

**Issue by jabusir** [darwin-education/resium#467]
Regardless of the view: 2D, Columbus View, or 3D, the part of the selected imagery (specifically the ones with text information) that isn't centered in the Viewer appears significantly larger than the part that is centered.

How can I make the fonts proportional as I zoom in across the entire Viewer? Is this something to do with my camera's positioning?

**Comment by rot1024** [comment]
Commonly country/city labels are included in tile map image data, so there is no way to adjust font styles directly. Consider using Mapbox to create customized styled tile map.

And this question is not related to Resium but Cesium. If you have more question about it, please ask it Cesium team.

**Comment by jabusir** [comment]
Once again. Thanks rot for you insightful response.
