### ISSUE TITLE
Which type should I pass to the Viewer ref?

### ISSUE THREAD

**Issue by otaviobps** [darwin-education/resium#469]
I'm trying to get the `Viewer` ref, but I'm using TypeScript. I tried

```
const cesium = useRef<CesiumComponentRef<ViewerProps>>(null)
```

But I get this error in the `ref` props:
> TS2322: Type 'RefObject<CesiumComponentRef<ViewerProps>>' is not assignable to type '((instance: CesiumComponentRef<Viewer> | null) => void) | RefObject<CesiumComponentRef<Viewer>> | null | undefined'.   Type 'RefObject<CesiumComponentRef<ViewerProps>>' is not assignable to type 'RefObject<CesiumComponentRef<Viewer>>'.     Type 'CesiumComponentRef<ViewerProps>' is not assignable to type 'CesiumComponentRef<Viewer>'.       Type 'ViewerProps' is missing the following properties from type 'Viewer': container, bottomContainer, cesiumWidget, dataSourceDisplay, and 18 more.  index.d.ts(140, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & {} & { terrainProvider?: TerrainProvider | undefined; terrainShadows?: ShadowMode | undefined; clockTrackedDataSource?: DataSource | undefined; ... 7 more ...; useBrowserRecommendedResolution?: boolean | undefined; } & ... 6 more ... & RefAttributes<...>'

How should I get the ref of the component in TypeScript?

**Comment by rot1024** [comment]
❌ ViewerProps
✅ Viewer (import from Cesium)

**Comment by otaviobps** [comment]
Thanks
