### ISSUE TITLE
Lazy load Cesium

### ISSUE THREAD

**Issue by otaviobps** [darwin-education/resium#470]
I followed the instructions and I'm running Resium with `craco`.

It's working fine, however when I load the app it already fetches the `Cesium.js` which has more than 1mb.

I only use Resium in the `/explorer` route. I'm already lazy loading the component using

```
const Explorer = lazy(() =>
    import("../pages/explorer").then((module) => ({ default: module.Explorer }))
  );
```

Is it possible to only load the `Cesium.js` when entering this route?

**Comment by rot1024** [comment]
Does loadPartial option not work?

**Comment by otaviobps** [comment]
> Does loadPartial option not work?

It did, thanks!
