### ISSUE TITLE
Layer imagery order

### ISSUE THREAD

**Issue by dcp3450** [darwin-education/resium#51]
I have a bing street map being loaded with openWeather tiles applied for weather:

```
const ionBing = new Cesium.IonImageryProvider({assetId: 4})
<ImageryLayerCollection>
  <ImageryLayer imageryProvider={ionBing} />
  <ImageryLayer imageryProvider={this.state.openWeatherOptions.temp} />
  <ImageryLayer imageryProvider={this.state.openWeatherOptions.clouds} />
</ImageryLayerCollection>
```

This sets the bing map over the openWeather tiles but placing it last gives the same result. Sometimes the temp tiles will show over the map but the clouds don't.

**Comment by dcp3450** [comment]
when the globe loaded you can see the temp and cloud layers briefly then the ionBing map loaded over it.

**Comment by rot1024** [comment]
Hmm... I tried following code and confirmed it works.

Following code is based on [src/stories/ImageryLayer.stories.tsx](https://github.com/darwin-education/resium/tree/master/src/stories/ImageryLayer.stories.tsx).

```jsx
import React from "react";
import { ArcGisMapServerImageryProvider, IonImageryProvider } from "cesium";
import { storiesOf } from "@storybook/react";

import Viewer from "../Viewer";
import ImageryLayer from "../ImageryLayer";

const ionBing = new IonImageryProvider({ assetId: 4 });
const night = new IonImageryProvider({ assetId: 3812 });

export default () => {
  storiesOf("ImageryLayer", module).add("default", () => (
    <Viewer full>
      <ImageryLayer imageryProvider={ionBing} />
      <ImageryLayer alpha={0.8} imageryProvider={night} />
    </Viewer>
  ));
};
```

![image](https://user-images.githubusercontent.com/3888696/51228837-6ebdc080-199d-11e9-923d-443a039fe5a8.png)

**Comment by rot1024** [comment]
Please let me know when you have still an issue .
