### ISSUE TITLE
Setting clock option doesn't affect timeline

### ISSUE THREAD

**Issue by dcp3450** [darwin-education/resium#53]
When setting the start, stop, and current settings for the lock the animation responds as expected but the timeline doesn't show those settings:

`<Clock startTime={Cesium.JulianDate.fromIso8601("2013-12-25")}  stopTime={Cesium.JulianDate.fromIso8601("2013-12-26")} currentTime={Cesium.JulianDate.fromIso8601("2013-12-25")} />`

**Comment by rot1024** [comment]
This behavior is normal. Calling some methods of the timeline is required.

```js
timeline.updateFromClock();
timeline.zoomTo(clock.startTime, clock.stopTime);
```

Example:

```jsx
class Example extends React.PureComponent {

  viewer = React.createRef();
  startTime = Cesium. fromIso8601("2013-12-25");
  stopTime = Cesium. fromIso8601("2013-12-26");
  currentTime = Cesium.JulianDate.fromIso8601("2013-12-25");

  componentDidMount() {
    viewer.cesiumElement.timeline.updateFromClock();
    viewer.cesiumElement.timeline.zoomTo(this.startTime, this.stopTime);
  }

  render() {
    return (
      <Viewer ref={this.viewer}>
        <Clock startTime={this.startTime} stopTime={this.stopTime} currentTime={this.currentTime} />
      </Viewer>
    );
  }

}
```

**Comment by dcp3450** [comment]
Had to fix an issue in the `ref` on `<Viewer />` Also, I have to access timeline this way, `viewer.current.cesiumElement.timeline`. However, there isn't an "updateFromClock()" method there...

**Comment by dcp3450** [comment]
It was some confusion on my side. The only thing I had to do different was use `current` like this: 

`viewer.current.cesiumElement.timeline`
