### ISSUE TITLE
Cesium Viewer entities add throwing error undefinded

### ISSUE THREAD

**Issue by Hector7500** [darwin-education/resium#54]
Cesium.Viewer.entities.add({...});

Throwing error
Cannot read property 'add' of undefined 

Tried EnitityColletion and single entities both return the error even if there is no viewer like Cesium.entites.add({...});

Is there something else that is supposed to be there?

**Comment by rot1024** [comment]
Is this question related to resium?

If you are looking into basic usage of Cesium, cesium official website is recommended.

**Comment by rot1024** [comment]
If you just want to access to `entities`, you can do it as following:

```jsx
class Comp extends React.PureComponent {

  viewer = React.createRef();

  componentDidMount() {
    const entities = this.viewer.current.cesiumElement.entities; // this is viewer.entities
    console.log(entities);
  }

  render() {
    return (
      <Viewer ref={this.viewer}/>
    );
  }

}
```

See also "Accessing to a Cesium element" in [Resium guide](https://resium.darwineducation.com/guide).

Did I answer your question?

**Comment by Hector7500** [comment]
yes thank you
