### ISSUE TITLE
Render map have different color than request image

### ISSUE THREAD

**Issue by Cootcha** [darwin-education/resium#55]
When i start app, i call ImageryLayers and get images, but color of images is different.
this is image from Chrome developer tools -> network 
![mapcacherp](https://user-images.githubusercontent.com/40633865/51245348-a91c6300-1987-11e9-80fa-d6a2fccac33f.png)
and this is screen from Resium
![snimek obrazovky porizeny 2019-01-16 11-57-04](https://user-images.githubusercontent.com/40633865/51245404-d49f4d80-1987-11e9-85dd-c4faef7afc2c.png)

ImageryLayer have default params (alpha, contrast, hue,..)
All resium components like Viewer, Scene, Globe have default params, only Fog and SkyAtmosphere are disabled.

**Comment by rot1024** [comment]
This issue may be caused by Cesium, not Resium. Please provide the code to reproduce that issue.

**Comment by Cootcha** [comment]
Oh. My fault. I forgot, that when i changed cesium-react to resium, that i changed cesium 1.51 to 1.53. When i install older version of cesium, all works great.

**Comment by rot1024** [comment]
Ok.
