### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by galleon** [darwin-education/resium#59]
I don't know if this is related to #52 but this is frustrating.
Can some basic doc be hosted on github to avoid that ?

Thanks for the great tool

**Comment by rot1024** [comment]
Hi, I just now tried to access the website, but I could not confirm it is down. It seems to be alive in my internet.

Please try removing caches. 

The website is hosted on Netlify.

**Comment by galleon** [comment]
Seems to be available now.
