### ISSUE TITLE
Use Cesium user token rather than the default ion access token

### ISSUE THREAD

**Issue by ale-cristofori** [darwin-education/resium#60]
When using the Viewer component in Resium there is a message on the the bottom saying 
"_This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken_..."

I was wondering if it would be possible to insert my own Cesium token.

**Comment by rot1024** [comment]
Just do it in entry point such as index.js:

```js
import Cesium from "cesium";

Cesium.Ion.defaultAccessToken = "YOUR_ACCESS_TOKEN";

ReactDOM.render(
  // ...
)
```

**Comment by utkarsh447** [comment]
> ```js
> import Cesium from "cesium";
> Cesium.Ion.defaultAccessToken = "YOUR_ACCESS_TOKEN";
> ```

Import of `Cesium` was returned as `undefined`. 
Rather, do this
```
import { Ion } from "cesium";
Ion.defaultAccessToken = "YOUR_ACCESS_TOKEN";
```

**Comment by badoubadou** [comment]
Hello, I did that too, but I still have the "This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken..."
Did something change ?
It's kind of weird because I can display my own asset from cesium ion, which I can't if I remove this line. So it's working, but not completely ?

**Comment by janhartmann** [comment]
Facing the same issue as @badoubadou

**Comment by salahelfarissi** [comment]
Hi, I have the same problem.

**Comment by yanhanruan** [comment]
> Hello, I did `Ion.defaultAccessToken = "YOUR_ACCESS_TOKEN";` but I still have the "This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken..." Did something change ? It's kind of weird because I can display my own asset from cesium ion, which I can't if I remove this line and run with the default AccessToken. So it's working, but not completely ?

I solved this problem by encapsulating the token into the defaultAccessToken attribute. The complete code is as follows：
`import { Ion } from "cesium";

const Ion.defaultAccessToken = "YOUR_TOKEN";
const Map = () => {
    return (<Viewer defaultAccessToken = {Ion}> <Viewer/>)
}
`

**Comment by AddictArts** [comment]
Unfortunately the below is not a thing or Viewer removed that attribute at some point. The cesium docs have the above methods `Cesium.Ion.defaultAccessToken` or `Ion.defaultAccessToken` depending on how you've included the cesium source.

> ```
> import { Ion } from "cesium";
> Ion.defaultAccessToken = "YOUR_TOKEN";
> const Map = () => {
>     return (<Viewer defaultAccessToken = {Ion}> <Viewer/>);
> }
> export default Map;
> ```

**Comment by yanhanruan** [comment]
> Unfortunately the below is not a thing or Viewer removed that attribute at some point. The cesium docs have the above methods `Cesium.Ion.defaultAccessToken` or `Ion.defaultAccessToken` depending on how you've included the cesium source.
> 
> > ```
> > import { Ion } from "cesium";
> > Ion.defaultAccessToken = "YOUR_TOKEN";
> > const Map = () => {
> >     return (<Viewer defaultAccessToken = {Ion}> <Viewer/>);
> > }
> > export default Map;
> > ```

yeah, you are right, I checked the source code of "Viewer" component, the "defaultAccessToken " attribute does not exist

**Comment by xinaesthete** [comment]
I haven't managed to make it use my token... may do a bit more poring over the code to see what's going on.

**Comment by AddictArts** [comment]
> I haven't managed to make it use my token... may do a bit more poring over the code to see what's going on.

If this helps, the following works well with the latest.

```
import { PropsWithChildren } from "react";
import { Ion } from "cesium";

export const AccessToken = (props: PropsWithChildren) => {
  Ion.defaultAccessToken =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5NDg2OTdhZS1hNTUyLTQ5ZWYtYmFiZi03MTZlZGNkNDA4ZWUiLCJpZCI6MzA1NiwiaWF0IjoxNTM1NzQyOTI0fQ.TEKgvImwDALg3bRLYXWYsvFKIfdxj9TU_np1QZjc6DI";

  return props.children;
}
```

Use it like the following

```
export function AppViewer() {
  return (
    <AccessToken>
      <Viewer
        animation={false}
        timeline={false}
      >
      </Viewer>
    </AccessToken>
  );
}

```
