### ISSUE TITLE
Resium workshop will be held at FOSS4G-NA 2019

### ISSUE THREAD

**Issue by rot1024** [darwin-education/resium#72]
Hi, everyone.

Resium workshop will be held at [FOSS4G-NA 2019](https://2019.foss4g-na.org/). If you are convenient, please feel free to attend it!

**Workshop Repository**

https://github.com/darwin-education/resium-workshop

**Workshop Program**

In this workshop, I’ll tell you how to use Resium, and we’ll work on building a Japanese archaic map archive. Target is anyone who have been interested in web front-end, React, or Cesium. Resium is a new library, abstracting Cesium functions as React components, and helping to build a rich web 3D GIS web-application faster.

**Comment by ksrb** [comment]
I should probably just ask the event organizer but first time hearing of this event, I just signed up for your workshop and it seems to be free? But then on the ticketing on https://ti.to/foss4g-na-2019/foss4g-na-2019-san-diego says the workshop day is $100.

So can I go to your workshop without paying the ticket?

**Comment by ksrb** [comment]
Okay I asked the event organizers you have to pay the $100 and can go to any workshop on that day. Not sure what's going on with the free signup maybe a limit on the number of attendees?

**Comment by rot1024** [comment]
Unfortunately FOSS4G admission is not free. You have to buy a ticket.

> Feel free to attend it!

It means "take it easy" to attend our workshop. FOSSS4G itself is not free (paid).

**Comment by kurohune538** [comment]
Thank you for your coming guys!
@everyone
@everyone
We are very happy to see you!
And we are going to improve Resium and other our OSS more!
So if you are interested in contribution, never mind to commit! we are waiting for your commit!

Thank you
