### ISSUE TITLE
Advanced use of EntityDescription 

### ISSUE THREAD

**Issue by spotnape** [darwin-education/resium#73]
I have a question about how to use the _EntityDescription_ which I appreciate may be difficult in Cesium too. Your advice would be most welcome. I'd like to have an entity description including a button which, when clicked, will activate a function on the page that performs a `props.history.push()` in order to cause router navigation. I've got as far as to understand that the description on the Cesium object works with an _iframe_ and further more that the Resium code works with `ReactDOM.renderToStaticMarkup`. There is some hint on the forums at there being a workaround possible with Cesium including some kind of configuration change to allow the iframe to perform javascript type events, but I've yet to be able to put this together with my principally Resium-built application. Do you know if this is possible?

**Note:** Replacing the Cesium configuration change with just `infoBoxEvents={true}` on the Viewer or some such configuration option would be great, but I appreciate of course that this may be a pretty unique request and not worthy of such a change.

Thank you for putting together this super library.

**Comment by rot1024** [comment]
Thank you for suggestion! I have also ever considered it.

Using react portal perhaps work well. I'll try to implement it.

References:

- https://stackoverflow.com/questions/34743264/how-to-set-iframe-content-of-a-react-component
- https://groups.google.com/forum/#!topic/cesium-dev/PKwsDiRDVOo

**Comment by rot1024** [comment]
Hi, new EntityDescription component is available in v1.10.0! In this version, it uses React Portal, so you can events or dynamic state in description of Entity. Try it!

Example: https://resium.darwineducation.com/examples/?path=/story/entity--description

**Comment by NirAbel** [comment]
Hello,
i'm trying to use Button inside EntityDescription but i can't understand how to change the button color and size, i want to implement a button block for all the size of the Entity box.. is it possible?
thank you!
Nir

**Comment by rot1024** [comment]
you can use CSS

```jsx
<EntityDescription>
  <style>{`
    .button {
      witdh: 100%;
    }
  `}</style>
  <button className="button" style={{ width: "100%" }}>OK</button>
</EntityDescription>
```
