### ISSUE TITLE
Add Storybook field to set Cesium.Ion.defaultAccessToken

### ISSUE THREAD

**Issue by jimklo** [darwin-education/resium#81]
After some time, the default access token expires and Cesium Ion stops functioning.

It would be nice if the user could override this, so when accessing the examples at https://resium.darwineducation.com/examples/ we could just set our own user token somewhere and it be used so the examples work properly and consistently.

**Comment by rot1024** [comment]
Hi, I've been fixed it, and now storybook is available. Thanks!
