### ISSUE TITLE
Suggesting new features 

### ISSUE THREAD

**Issue by imvan32** [darwin-education/resium#84]
Hello. Your library is good. I want to take part in your project and I have some ideas like:

- Make more tests, stories and examples with other libraries. For example  "Hello world" or something more complicated.

- Change the structure of the project something like this:
```
project 
│
└─── src
│   └─── Entity
│       │   index.ts
│       │   Entity.ts
│       │   Entity.stories.tsx
│       │   Entity.test.tsx
│       │   index.md
│   
|   └─── PolylineGraphics
│       │   index.ts
│       │   PolylineGraphics.ts
│       │   PolylineGraphics.stories.tsx
│       │   PolylineGraphics.test.tsx
│       │   index.md
```
If you are interested in this, I'm ready to help you.
Thanks =)

**Comment by kurohune538** [comment]
> Make more tests, stories and examples with other libraries. For example "Hello world" or something more complicated.
We would like to make them more. So we are welcome you to join our contribution! Thank you

> Change the structure of the project something like this:
We gonna think about it soon.

**Comment by rot1024** [comment]
Thank you for your contributing! I think the project structure you suggested is more clean than the current code. 

BTW I plan to reimplement the core with React Hooks. So at first, we shall get started with changing structure only. We are waiting for your PR!

**Comment by imvan32** [comment]
Good. I'll sent you PR on the next week (or in the beginning of the next week), okay?

**Comment by rot1024** [comment]
Great.
