### ISSUE TITLE
custom ui buttons

### ISSUE THREAD

**Issue by jvarada** [darwin-education/resium#85]
What is the recommended way to create custom UI buttons in Resium (namely buttons in the 'cesium-viewer-toolbar'). From the Cesium API I see you can assign a component to the SceneModelPicker/Geocoder/etc , but I can't find anything similar in the Resium docs.

**Comment by rot1024** [comment]
For now, APIs for custom buttons is not ready, as they are powered by knockout.js not React. But you can add UIs as following.

1. Remove default buttons and add new buttons on the top of Viewer with React way

```jsx
const Example = () => {
  const viewer = React.useRef(null);
  return (
    <Viewer ref={viewer} homeButton={false}>
      <button
        onClick={() => {
          viewer.current.cesiumElement.camera.flyHome();
        }}>
        Home
      </button>
    </Viewer>
  );
};
```

2. (Similar to 1) Create a new component

```jsx
const { CesiumContext } from "resium";

const HomeButton = () => {
  const cesium = React.useContext(CesiumContext);
  return (
    <button
      onClick={() => {
        if (!cesium || !cesium.viewer) return;
        cesium.viewer.camera.flyHome();
      }}>
      Home
    </button>
  );
};

export default HomeButton;
```

and use it:

```jsx
import HomeButton from "./homeButton";

<Viewer homeButton={false}>
  <HomeButton />
</Viewer>
```

**Comment by PieterBoeren** [comment]
For me, this does not work, all the components I add inside the `<Viewer>` are rendered below the canvas, unless I set the viewer to `full`. Is there any way other way to add buttons to the toolbar?

**Comment by rot1024** [comment]
Omitted in above examples, but specifying styles is required to display elements in Viewer.

```jsx
<VIeiwer>
	<div style={{ position: "absolute", top: "0", left: "0" }} />
</Vieiwer>
```

**Comment by PieterBoeren** [comment]
But it is also possible **without** the `full`?

**Comment by CLBID** [comment]
We used a side nav bar and were able to put the buttons, and other controls like textboxes, etc in the side nav.
Maybe that will help you out.   I was never able to get it on the map.  We were able to have a mouse cursor move label.   We used <paper> in order to do it.  It moves as the cursor moves.
