### ISSUE TITLE
Setting default location?

### ISSUE THREAD

**Issue by mrlubos** [darwin-education/resium#86]
Hey,

Looking at the code for setting default location for the map.

```js
var west = 122.0;
var south = 33.0;
var east = 130.0;
var north = 47.0;

var rectangle = Cesium.Rectangle.fromDegrees(west, south, east, north);

Cesium.Camera.DEFAULT_VIEW_FACTOR = 0;
Cesium.Camera.DEFAULT_VIEW_RECTANGLE = rectangle;

// NOTE: Viewer constructed after default view is set.
var viewer = new Cesium.Viewer('cesiumContainer');
```

Is it possible to achieve this in the current version of Resium? I cannot find references to either of these attributes. Thank you for your help!

Source: https://gis.stackexchange.com/questions/144361/how-to-set-the-coordinates-at-which-cesium-viewer-is-centered

**Comment by spotnape** [comment]
You can achieve this using **Camera** and **CameraFlyTo** with a duration of 0 like this, where _destination_ can be a variety of Cesium options including a **Rectangle** I believe.

```
<Camera defaultZoomAmount={0} />
<CameraFlyTo duration={0} destination={destination} />
```

A Cartesian3 object such as this certainly works nicely here.

```
Cartesian3.fromDegrees(11, 26, 40200000)
```

**Comment by mrlubos** [comment]
I'll give it a try, thank you @spotnape!
