### ISSUE TITLE
clustering CustomDataSource: length undefined

### ISSUE THREAD

**Issue by jarnovanrhijn** [darwin-education/resium#9]
Hi,

I'm trying to enable clustering in the <CustomDataSource/> component. however i'm getting the following error 
<img width="1270" alt="screen shot 2018-07-30 at 10 23 17" src="https://user-images.githubusercontent.com/2767127/43386063-caac8818-93e2-11e8-9b89-5e3ce57718f3.png">

quick example of my render method:

```
       
      <Viewer
        full
        baseLayerPicker={false}
        infoBox={false}
        homeButton={false}
        animation={false}
        timeline={false}
        scene3DOnly={true}
        shadows={true}
        fullscreenButton={false}
        onSelectedEntityChanged={e => this.flyTo(e)}
        selectionIndicator={false}
        imageryProvider={this.renderImageryProvider()}
        ref={e => {
          this.viewer = e ? e.cesiumElement : null;
        }}
      >
        <ScreenSpaceCameraController
          maximumZoomDistance={20000}
          minimumZoomDistance={50000000}
        />
        <CustomDataSource
          name="customDataSourceThing"
          clustering={{
            enabled: true,
            pixelRange: 15,
            minimumClusterSize: 3,
            clusterBillboards: true,
            clusterLabels: false,
            clusterPoints: false
          }}
          show={true}
        >
          <Entity
            name="customDataSourceThing"
            description="test"
            position={Cartesian3.fromDegrees(-74.0707383, 41.7117244, 100)}
            point={{ pixelSize: 10 }}
          />
        </CustomDataSource>
      </Viewer>
```

Let me know if you need more details regarding the example?

Regards, Jarno

**Comment by rot1024** [comment]
This bug will be fixed in v1.0.0. Please set clustering prop as bellow. 

```jsx
<CustomDataSource
  clustering={new EntityCluster({
    enabled: true,
    pixelRange: 15,
    minimumClusterSize: 3,
    clusterBillboards: true,
    clusterLabels: false,
    clusterPoints: false
  })}>
```

See also:

**Comment by rot1024** [comment]
Hi, I've released resium v1.0.0. Please try it!

**Comment by jarnovanrhijn** [comment]
Sorry for the late reply :) but this still is not working.. getting length of undefined
<img width="1448" alt="screenshot 2019-02-18 at 20 52 25" src="https://user-images.githubusercontent.com/2767127/52973681-20964580-33bf-11e9-8b88-993199cdb459.png">

**Comment by rot1024** [comment]
Sorry for late reply.

Please try `clustering={new EntityCluster({ ... })}` instead of `clustering={{ ... }}`:

```jsx
import { EntityCluster } from "cesium";

<CustomDataSource
  clustering={
    new EntityCluster({
      enabled: true,
      pixelRange: 50,
      minimumClusterSize: 3,
      clusterPoints: true,
    })
  }>
```

**Comment by rot1024** [comment]
Also refer to [EntityCluster example](https://resium.darwineducation.com/examples/?path=/story/customdatasource--entity-clustering)

**Comment by jarnovanrhijn** [comment]
Thanks for all the work and help!! Will look at the examples

**Comment by riccardolardi** [comment]
Is there a new EntityCluster example? e.g. has this been resolved?
