### ISSUE TITLE
Changing text of labels in a collection

### ISSUE THREAD

**Issue by raufdean** [darwin-education/resium#92]
Having a few problems with Label Collections/ Labels. I'm passing a string into the text prop of the Label but it isn't updating when the property changes. Are labels editable or do I have to manually remove them and then add them again to a collection ? Thanks

**Comment by raufdean** [comment]
Having a few problems with Label Collections/ Labels. I'm passing a string into the text prop of the Label but it isn't updating when the property changes. Are labels editable or do I have to manually remove them and then add them again to a collection ? Thanks

**Comment by rot1024** [comment]
Hi, thank you for reporting! I found a bug in Resium and I have fixed it. 

Please wait for the next release to enable updating Label properties as intended. 

Thanks.

**Comment by raufdean** [comment]
Thanks, I worked round the issue for the time being by using labels in entities..

**Comment by rot1024** [comment]
v1.5.0 has been released!
