### ISSUE TITLE
terrainExaggeration not working

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#93]
Hi,

I'm trying to set up a terrainExaggeration={3} within my <Scene> component:

<Scene
..
terrainExaggeration={3}
'>

In my Viewer I'm using terrainProvider={ionTerrainProvider}

Anyway, I got this error: 

TypeError: Cannot set property terrainExaggeration of #<Pe> which has only a getter

Any ideas?

**Comment by rot1024** [comment]
Cesium document says that we cannot change terrainExaggeration after the viewer and scene are created.

If you really need it, you can change terrainExaggeration property in Viewer. But it is marked as "read only props", so Viewer will be recreated every it is changed.

**Comment by pyonono** [comment]
Thanks,
