### ISSUE TITLE
Destroying an entity

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#95]
By updating the 'show' property to True or False, you can show/turn off the entity in your Viewer.

However, if you want to destroy it completely, I have seen examples in SandCastle in which you can add and remove entities:

viewer.entities.add
viewer.entities.remove

So, if you create an entity in Resium, like this:

`createPoint(worldPosition){
		return (
			<Entity name="test-point" description="My point!" position={worldPosition}>
				<PointGraphics
					color={Color.WHITE}
					pixelSize={5}
					heightReference={HeightReference.CLAMP_TO_GROUND}
				/>
			</Entity>
		)
	};`

How would you destroy it?

**Comment by rot1024** [comment]
if you want to remove component completely, return `null` in render time. It is common in React.

```jsx
cosnt Component = ({ show }) => {
  return show ? <Entity>{/* ... */}</Entity> : null;
};
```

**Comment by pyonono** [comment]
Thanks,

**Comment by BeyondBelief96** [comment]
import { Entity, Viewer } from 'resium';
import './App.css';
import { useState } from 'react';
import { Cartesian3 } from 'cesium';

function App() {
  const airportLocations = [
    { id: 1, longitude: -74.0707383, latitude: 40.7117244, altitude: 100 },
    { id: 2, longitude: -122.3748889, latitude: 37.6189722, altitude: 200 },
    { id: 3, longitude: -87.9073244, latitude: 41.9786111, altitude: 300 },
    // Add more airport locations as needed
  ];

  const [showEntity, setShowEntity] = useState(false);

  function handleToggle() {
    setShowEntity(!showEntity);
  }

  return (
    <div style={{ display: 'flex', height: '100vh' }}>
      <div style={{ width: '100px', backgroundColor: '#f0f0f0', padding: '10px' }}>
        <button onClick={handleToggle}>Toggle Entity</button>
      </div>
      <Viewer style={{ flexGrow: 1 }}>
        {showEntity ?
          airportLocations.map((airport) => (
            <Entity
              key={airport.id}
              position={Cartesian3.fromDegrees(airport.longitude, airport.latitude, airport.altitude)}
              point={{ pixelSize: 20 }}
            />
          )) : null}
      </Viewer>
    </div>
  );
}

export default App;

I have this code and the entities are not being removed from the viewer once being added. I can see in they are being removed from the react component tree, but I can still see and interact with the entitys in the cesium viewer.
