### ISSUE TITLE
Cesium3DTileset breaks when re-rendering the map

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#96]
Hi, I can add a Cesium3DTileset, but when using a checker or even a slider to alter/change its properties, i.e. show state

Then Resium breaks and I got a blank page, it only happens when using an asset from Ion, not with other types of data.

`handleIonTilesetShowChange = e => {
	e.target.checked ? (
		this.setState({IonTilesetShow: true})
	) : (
		this.setState({IonTilesetShow: false})
	)}
`
`<input id="IonTileset-checker" class="checkmark"
type="checkbox"	
checked={this.state.IonTilesetShow}
onChange={this.handleIonTilesetShowChange}
/>`
`<Cesium3DTileset
url={IonResource.fromAssetId(15885)}
show={this.state.IonTilesetShow}
/>`

**Comment by rot1024** [comment]
`url` property of Cesium3DTileset is "read only", so we cannot change after it is mounted. `IonResource.fromAssetId(15885)` returns a new Promise, so url property will be changed every render time.

So, please bind the resource to a variable.

```jsx
class Test extends React.Component {
  resouce = IonResource.fromAssetId(15885);

  render() {
    return <Cesium3DTileset url={this.resource} />
  }
}
```

**Comment by pyonono** [comment]
Thanks, I'll try this

**Comment by pyonono** [comment]
It works,

Thanks
