### ISSUE TITLE
Load new entities (points) dynamically

### ISSUE THREAD

**Issue by pyonono** [darwin-education/resium#98]
If we can add a point and render it when map loads:

`createPoint(coor){
		return (
			<Entity name="ABC" description="first point" position={coor}>
				<PointGraphics
					color={Color.RED}
					pixelSize={5}
				/>
			</Entity>
		)
	};`

and then,

`render() {
		return (	
			<Viewer>
					{this.createPoint(coor)}
                        </Viewer>`

How can we CREATE in resium new points (a second, third, etc.) dynamically (i.e. by clicking) but without updating/modifying the previous ones, so we can have them all onto the map?

Is there any concept of an array of entities?

**Comment by rot1024** [comment]
I postulate type of `coors` is `Cartesian3[]`.

```jsx
const Point = ({ coor }) => (
  <Entity name="ABC" description="first point" position={coor}>
    <PointGraphics color={Color.RED} pixelSize={5} />
  </Entity>
);

const App = ({ coors }) => (
  <Viewer>
    {coors.map((c, i) => (
      <Point coor={c} key={i} />
    )}
  </Viewer>
);
```

Are you beginner of React?  Before using Resium, I recommend to learn how to build a general app with React, such as to-do app.
