### ISSUE TITLE
How to update Billboard markers ?

### ISSUE THREAD

**Issue by yashug** [darwin-education/resium#99]
was trying to filter the billboard markers. but they are not getting updated either with show property or creating total new billboards?

`{data.map(item => (
            <Billboard
              key={item.id}
              show={item.showMarker}
            />
  ))}`

on data being changed billboards are not getting updated

**Comment by yashug** [comment]
so basically this comes down to, how to use billboardcollections removeall() method in resium. Need to remove already added billboards before rendering new billboards

**Comment by yashug** [comment]
@rot1024 can you please help me here

**Comment by rot1024** [comment]
Sorry for the late reply. It's a bug.

I have fixed the bug and released v1.6.0. Please try it!

Thank you.
